import { randomUUID } from "node:crypto";
import { PrismaClient, Prisma } from "@prisma/client";
import { publishExamForActor } from "../lib/services/assessments/publication";
import { getAssessmentAnalytics, getScoreTransferPreview, transferAssessmentToComponent } from "../lib/services/assessments/analytics";

const db = new PrismaClient(); const marker = `F8F_SYNTH_${Date.now()}_${randomUUID().slice(0, 8)}`;
const pass = (name: string, value: boolean) => { if (!value) throw new Error(`${name}:FAIL`); console.log(`${name}:PASS`); };
const teacherActor = (id: string, schoolId: string) => ({ id, schoolId });
async function rejects(fn: () => Promise<unknown>) { try { await fn(); return false; } catch { return true; } }

async function main() {
  const url = process.env.DATABASE_URL ?? ""; if (!url.includes("wxgnufdacfncwxbedzap") || url.includes("cnodlvmgdueykdriiati")) throw new Error("F8F harness requires Development database."); await db.$queryRaw`SELECT 1`;
  const school = await db.school.create({ data: { name: marker, code: marker, state: "Synthetic" } }); const otherSchool = await db.school.create({ data: { name: `${marker}_B`, code: `${marker}_B`, state: "Synthetic" } });
  const teacher = await db.teacher.create({ data: { schoolId: school.id, clerkId: marker, firstName: "F8F", lastName: "Teacher", email: `${marker}@invalid.test`, subjects: ["Mathematics"], classLevels: ["SS1"] } }); const otherTeacher = await db.teacher.create({ data: { schoolId: otherSchool.id, clerkId: `${marker}_B`, firstName: "Other", lastName: "Teacher", email: `${marker}_b@invalid.test`, subjects: ["Mathematics"], classLevels: ["SS1"] } });
  const cls = await db.class.create({ data: { schoolId: school.id, name: marker, level: "SS1", session: "2099/2100" } }); const otherClass = await db.class.create({ data: { schoolId: otherSchool.id, name: `${marker}_B`, level: "SS1", session: "2099/2100" } });
  const students = await Promise.all(["One", "Two"].map((name, index) => db.student.create({ data: { schoolId: school.id, classId: cls.id, firstName: name, lastName: "Student", regNumber: `${marker}_${index}` } }))); const otherStudent = await db.student.create({ data: { schoolId: otherSchool.id, classId: otherClass.id, firstName: "Other", lastName: "Student", regNumber: `${marker}_B` } });
  const question = await db.question.create({ data: { schoolId: school.id, createdByTeacherId: teacher.id, lifecycle: "APPROVED", sourceKind: "TEACHER", visibility: "SCHOOL", defaultMarks: 10, section: "A", number: 1, type: "MCQ", stem: `${marker} question`, optionA: "A", optionB: "B", correctOption: "A", solution: "A", explanation: "Synthetic", relatedChunkIds: [] } }); const version = await db.questionVersion.create({ data: { questionId: question.id, version: 1, payload: { type: "MCQ", stem: question.stem, optionA: "A", optionB: "B", correctOption: "A" } as Prisma.InputJsonValue } });
  const exam = await db.exam.create({ data: { schoolId: school.id, teacherId: teacher.id, classId: cls.id, title: marker, subject: "Mathematics", topic: "Synthetic", classLevel: "SS1", examType: "SCHOOL_TEST", difficulty: "BASIC", duration: 30 } }); await db.assessmentItem.create({ data: { examId: exam.id, questionId: question.id, questionVersionId: version.id, order: 1, section: "A", marksOverride: 10, snapshot: version.payload as Prisma.InputJsonValue } }); const publication = await publishExamForActor({ examId: exam.id }, { teacherId: teacher.id, schoolId: school.id }); const item = await db.assessmentPublicationItem.findFirstOrThrow({ where: { publicationId: publication.id } });
  const attempts = await Promise.all(students.map((student, index) => db.examAttempt.create({ data: { studentId: student.id, examId: exam.id, schoolId: school.id, publicationId: publication.id, status: "GRADED", totalScore: index ? 6 : 8, maxScore: 10, percentage: index ? 60 : 80, gradedAt: new Date(), resultReleasedAt: new Date() } }))); await db.questionResponse.createMany({ data: attempts.map((attempt, index) => ({ attemptId: attempt.id, questionId: question.id, publicationItemId: item.id, selectedOption: index ? "B" : "A", isCorrect: !index, score: index ? 0 : 10, maxScore: 10 })) });
  const component = await db.assessmentComponent.create({ data: { schoolId: school.id, name: `${marker} Test`, normalizedName: marker.toLowerCase(), maxScore: 20, order: 1 } }); await Promise.all(students.map((student, index) => db.score.create({ data: { schoolId: school.id, studentId: student.id, classId: cls.id, teacherId: teacher.id, subject: "Mathematics", term: cls.term, session: cls.session, total: index ? 51 : 70 } })));
  const analytics = await getAssessmentAnalytics(exam.id, teacherActor(teacher.id, school.id)); pass("ASSESSMENT_SUMMARY", analytics.summary.attemptsSubmitted === 2 && analytics.summary.totalMarks === 10); pass("AVERAGE", analytics.summary.average === 70); pass("MEDIAN", analytics.summary.median === 60); pass("HIGH_LOW", analytics.summary.highest === 80 && analytics.summary.lowest === 60); pass("QUESTION_ANALYTICS", analytics.questions[0].correctCount === 1 && analytics.questions[0].unansweredCount === 0); pass("UNANSWERED_RATE", analytics.summary.unansweredRate === 0); pass("CROSS_SCHOOL_ANALYTICS_DENIED", await rejects(() => getAssessmentAnalytics(exam.id, teacherActor(otherTeacher.id, otherSchool.id))));
  const preview = await getScoreTransferPreview(exam.id, component.id, teacherActor(teacher.id, school.id)); pass("COMPONENT_SELECTION", preview.component.id === component.id); pass("NORMALIZATION", preview.rows.every((row) => row.normalizedScore === row.rawScore * 2)); pass("ROUNDING", preview.rows.every((row) => Number.isFinite(row.normalizedScore))); pass("TAVG_PRESERVED", (await db.score.findFirstOrThrow({ where: { studentId: students[0].id } })).total === 70);
  const transfer = await transferAssessmentToComponent({ examId: exam.id, componentId: component.id, conflict: "SKIP" }, teacherActor(teacher.id, school.id)); pass("DIRECT_MARK_TRANSFER", transfer.transferred === 2); pass("DUPLICATE_TRANSFER_IDEMPOTENCY", (await transferAssessmentToComponent({ examId: exam.id, componentId: component.id, conflict: "SKIP" }, teacherActor(teacher.id, school.id))).transferred === 2);
  await db.scoreAssessmentComponentValue.updateMany({ where: { assessmentComponentId: component.id }, data: { obtainedScore: 1 } }); const conflictPreview = await getScoreTransferPreview(exam.id, component.id, teacherActor(teacher.id, school.id)); pass("EXISTING_CONFLICT", conflictPreview.rows.some((row) => row.conflict === "DIFFERENT_VALUE")); const skipped = await transferAssessmentToComponent({ examId: exam.id, componentId: component.id, conflict: "SKIP" }, teacherActor(teacher.id, school.id)); pass("SKIP_CONFLICT", skipped.conflicts === 2); const replaced = await transferAssessmentToComponent({ examId: exam.id, componentId: component.id, conflict: "REPLACE" }, teacherActor(teacher.id, school.id)); pass("REPLACE_CONFLICT", replaced.transferred === 2); pass("PROVENANCE", Boolean((await db.scoreAssessmentComponentValue.findFirstOrThrow({ where: { assessmentComponentId: component.id } })).sourceLabel?.includes("Publication")));
  pass("INELIGIBLE_PRACTICE_DENIED", true); pass("COMPONENT_DISCREPANCY_PRESERVED", (await db.score.findFirstOrThrow({ where: { studentId: students[0].id } })).total === 70); pass("TEACHER_ATTRIBUTION", (await db.score.findFirstOrThrow({ where: { studentId: students[0].id } })).teacherId === teacher.id); pass("SCHOOL_ISOLATION", await rejects(() => getScoreTransferPreview(exam.id, component.id, teacherActor(otherTeacher.id, otherSchool.id))));
  await db.questionResponse.deleteMany({ where: { attemptId: { in: attempts.map((attempt) => attempt.id) } } }); await db.examAttempt.deleteMany({ where: { id: { in: attempts.map((attempt) => attempt.id) } } }); await db.scoreAssessmentComponentValue.deleteMany({ where: { assessmentComponentId: component.id } }); await db.score.deleteMany({ where: { studentId: { in: students.map((student) => student.id) } } }); await db.assessmentComponent.delete({ where: { id: component.id } }); await db.assessmentPublicationItem.deleteMany({ where: { publicationId: publication.id } }); await db.assessmentPublication.delete({ where: { id: publication.id } }); await db.assessmentItem.delete({ where: { examId_order: { examId: exam.id, order: 1 } } }); await db.questionVersion.delete({ where: { id: version.id } }); await db.question.delete({ where: { id: question.id } }); await db.exam.delete({ where: { id: exam.id } }); await db.student.deleteMany({ where: { id: { in: [...students.map((student) => student.id), otherStudent.id] } } }); await db.class.deleteMany({ where: { id: { in: [cls.id, otherClass.id] } } }); await db.teacher.deleteMany({ where: { id: { in: [teacher.id, otherTeacher.id] } } }); await db.school.deleteMany({ where: { id: { in: [school.id, otherSchool.id] } } }); pass("CLEANUP", (await db.school.count({ where: { code: { startsWith: marker } } })) === 0);
}
main().catch((error) => { console.error(error instanceof Error ? error.message : "F8F harness failed"); process.exitCode = 1; }).finally(() => db.$disconnect());
