import { randomUUID } from "node:crypto";
import { PrismaClient, Prisma } from "@prisma/client";
import { createQuestionVersionAlignment } from "../lib/services/curriculum/alignment";
import { createHash } from "node:crypto";
import { createIngestionJob, fingerprintSource, normalizeExtractedItem, publishIngestionJob, registerCurriculumSource, reviewStagedItem, stageCurriculumItems, transitionIngestionJob, validateIngestionJob } from "../lib/services/curriculum/ingestion";

const db = new PrismaClient(); const marker = `F9C_SYNTH_${Date.now()}_${randomUUID().slice(0, 8)}`;
const pass = (name: string, value: boolean) => { if (!value) throw new Error(`${name}:FAIL`); console.log(`${name}:PASS`); };
const rejects = async (fn: () => Promise<unknown>) => { try { await fn(); return false; } catch { return true; } };

async function main() {
  const url = process.env.DATABASE_URL ?? ""; if (!url.includes("wxgnufdacfncwxbedzap") || url.includes("cnodlvmgdueykdriiati")) throw new Error("F9C harness requires Development database."); await db.$queryRaw`SELECT 1`;
  const school = await db.school.create({ data: { name: marker, code: marker, state: "Synthetic" } });
  const admin = await db.teacher.create({ data: { schoolId: school.id, clerkId: marker, firstName: "F9C", lastName: "Admin", email: `${marker}@invalid.test`, role: "ADMIN", subjects: ["Mathematics"], classLevels: ["SS2"] } });
  const teacher = await db.teacher.create({ data: { schoolId: school.id, clerkId: `${marker}_teacher`, firstName: "Ordinary", lastName: "Teacher", email: `${marker}_teacher@invalid.test`, role: "TEACHER", subjects: ["Mathematics"], classLevels: ["SS2"] } });
  const curriculum = await db.curriculum.create({ data: { slug: marker.toLowerCase(), name: `${marker} Curriculum`, authority: "Synthetic Authority", kind: "NATIONAL_CURRICULUM" } });
  const version1 = await db.curriculumVersion.create({ data: { curriculumId: curriculum.id, versionKey: "2025.1", title: `${marker} Edition 1`, status: "DRAFT" } });
  const version2 = await db.curriculumVersion.create({ data: { curriculumId: curriculum.id, versionKey: "2026.1", title: `${marker} Edition 2`, status: "DRAFT" } });
  const raw = Buffer.from(`${marker}\nSS2 Mathematics\nQuadratic Equations\nStudents should solve by factorisation.`);
  const fingerprint = fingerprintSource(raw); pass("SOURCE_FINGERPRINT", fingerprint === createHash("sha256").update(raw).digest("hex"));
  const registered = await registerCurriculumSource({ fingerprint, title: `${marker} source`, curriculumId: curriculum.id, sourceType: "OFFICIAL_DOCUMENT", authorityLevel: "UNKNOWN", mimeType: "text/plain", byteSize: raw.length }, { teacherId: admin.id, schoolId: school.id }); pass("SOURCE_REGISTRATION", !registered.duplicate);
  const duplicateSource = await registerCurriculumSource({ fingerprint, title: `${marker} source retry`, curriculumId: curriculum.id }, { teacherId: admin.id, schoolId: school.id }); pass("DUPLICATE_SOURCE", duplicateSource.duplicate && duplicateSource.source.id === registered.source.id);
  pass("UNAUTHORIZED_REGISTRATION", await rejects(() => registerCurriculumSource({ fingerprint: `${fingerprint}x`, title: "no", curriculumId: curriculum.id }, { teacherId: teacher.id, schoolId: school.id })));
  const jobResult = await createIngestionJob({ sourceId: registered.source.id, curriculumVersionId: version1.id, rawHash: fingerprint }, { teacherId: admin.id, schoolId: school.id }); const job = jobResult.job; pass("INGESTION_JOB_CREATE", !jobResult.duplicate && job.state === "REGISTERED");
  pass("JOB_STATE_TRANSITIONS", (await transitionIngestionJob(job.id, "VALIDATING", { teacherId: admin.id, schoolId: school.id })).state === "VALIDATING" && (await transitionIngestionJob(job.id, "EXTRACTING", { teacherId: admin.id, schoolId: school.id })).state === "EXTRACTING" && (await transitionIngestionJob(job.id, "NORMALIZING", { teacherId: admin.id, schoolId: school.id })).state === "NORMALIZING");
  const items = [{ stableKey: "ss2.math", type: "SUBJECT" as const, label: "Mathematics", rawText: "SS2 Mathematics", subject: "Mathematics", classLevel: "SS2" as const, term: "SECOND" as const, sourcePage: "1" }, { stableKey: "ss2.math.quadratics", parentStableKey: "ss2.math", type: "TOPIC" as const, label: " Quadratic   Equations ", rawText: "Quadratic Equations", subject: "Mathematics", classLevel: "SS2" as const, term: "SECOND" as const, sourcePage: "2" }, { stableKey: "ss2.math.quadratics.factor", parentStableKey: "ss2.math.quadratics", type: "LEARNING_OBJECTIVE" as const, label: "Solve by factorisation", rawText: "Students should solve by factorisation.", subject: "Mathematics", classLevel: "SS2" as const, term: "SECOND" as const, sourceSection: "Objectives" }];
  pass("RAW_EXTRACTION_PRESERVATION", items[2].rawText.includes("Students should")); pass("NORMALIZATION", normalizeExtractedItem(items[1]).label === "Quadratic Equations");
  await stageCurriculumItems(job.id, items, { teacherId: admin.id, schoolId: school.id }); pass("STAGING", (await db.curriculumStagedItem.count({ where: { jobId: job.id } })) === 3); pass("JOB_NEEDS_REVIEW", (await db.curriculumIngestionJob.findUniqueOrThrow({ where: { id: job.id } })).state === "NEEDS_REVIEW");
  const validation = await validateIngestionJob(job.id, { teacherId: admin.id, schoolId: school.id }); pass("VALIDATION_WARNING", validation.warnings.length === 0); pass("VALIDATION_BLOCKER", (await stageCurriculumItems(job.id, [{ stableKey: "bad", type: "TOPIC", label: "", rawText: "" }], { teacherId: admin.id, schoolId: school.id }).then(() => validateIngestionJob(job.id, { teacherId: admin.id, schoolId: school.id }))).blockers.length > 0);
  await db.curriculumStagedItem.delete({ where: { jobId_stableKey: { jobId: job.id, stableKey: "bad" } } });
  const candidate = await db.curriculumStagedItem.findUniqueOrThrow({ where: { jobId_stableKey: { jobId: job.id, stableKey: "ss2.math.quadratics.factor" } } }); const edited = await reviewStagedItem({ id: candidate.id, expectedRevision: candidate.reviewRevision, decision: "EDIT", label: "Solve quadratic equations by factorisation", normalizedText: "Students should solve quadratic equations by factorisation.", reviewNotes: "Preserved source wording." }, { teacherId: admin.id, schoolId: school.id }); pass("REVIEW_EDIT", edited.reviewState === "EDITED"); pass("STALE_APPROVAL_DENIAL", await rejects(() => reviewStagedItem({ id: edited.id, expectedRevision: candidate.reviewRevision, decision: "APPROVE" }, { teacherId: admin.id, schoolId: school.id })));
  for (const item of await db.curriculumStagedItem.findMany({ where: { jobId: job.id } })) { const current = await db.curriculumStagedItem.findUniqueOrThrow({ where: { id: item.id } }); await reviewStagedItem({ id: item.id, expectedRevision: current.reviewRevision, decision: "APPROVE" }, { teacherId: admin.id, schoolId: school.id }); }
  pass("REJECT", (await reviewStagedItem({ id: edited.id, expectedRevision: (await db.curriculumStagedItem.findUniqueOrThrow({ where: { id: edited.id } })).reviewRevision, decision: "REJECT" }, { teacherId: admin.id, schoolId: school.id })).reviewState === "REJECTED");
  // Re-approve after explicit review decision.
  const rejected = await db.curriculumStagedItem.findUniqueOrThrow({ where: { id: edited.id } }); await reviewStagedItem({ id: rejected.id, expectedRevision: rejected.reviewRevision, decision: "APPROVE" }, { teacherId: admin.id, schoolId: school.id });
  const published = await publishIngestionJob(job.id, { teacherId: admin.id, schoolId: school.id }); pass("APPROVAL", published.count === 3); pass("PUBLICATION", published.published === true); pass("PUBLICATION_TRANSACTION", (await db.curriculumNode.count({ where: { curriculumVersionId: version1.id } })) === 3); const retry = await publishIngestionJob(job.id, { teacherId: admin.id, schoolId: school.id }); pass("PUBLICATION_IDEMPOTENCY", retry.duplicate === true && retry.count === 3); pass("HIERARCHY", (await db.curriculumEdge.count({ where: { relationship: "PART_OF", source: { curriculumVersionId: version1.id } } })) === 2);
  const unchanged = await createIngestionJob({ sourceId: registered.source.id, curriculumVersionId: version1.id, rawHash: fingerprint }, { teacherId: admin.id, schoolId: school.id }); pass("REIMPORT_UNCHANGED", unchanged.duplicate === true && unchanged.job.id === job.id); const changed = await createIngestionJob({ sourceId: registered.source.id, curriculumVersionId: version2.id, rawHash: `${fingerprint}-changed` }, { teacherId: admin.id, schoolId: school.id }); pass("REIMPORT_CHANGED", changed.duplicate === false && changed.job.revision === 2);
  const question = await db.question.create({ data: { schoolId: school.id, createdByTeacherId: teacher.id, lifecycle: "APPROVED", sourceKind: "TEACHER", visibility: "SCHOOL", section: "A", number: 1, type: "MCQ", stem: marker, solution: "A", explanation: "Synthetic", relatedChunkIds: [] } }); const qv = await db.questionVersion.create({ data: { questionId: question.id, version: 1, payload: { stem: marker } as Prisma.InputJsonValue } }); const align = await createQuestionVersionAlignment({ questionVersionId: qv.id, curriculumNodeId: (await db.curriculumNode.findFirstOrThrow({ where: { curriculumVersionId: version1.id, stableKey: "ss2.math.quadratics.factor" } })).id, curriculumVersionId: version1.id, status: "APPROVED" }, { teacherId: admin.id, schoolId: school.id }); pass("QUESTIONVERSION_ALIGNMENT_PRESERVED", align.questionVersionId === qv.id && (await db.questionVersionCurriculumAlignment.count({ where: { questionVersionId: qv.id } })) === 1); pass("VERSION_IMMUTABILITY", (await db.curriculumVersion.findUniqueOrThrow({ where: { id: version1.id } })).title === `${marker} Edition 1`); pass("DUPLICATE_NODE_SAFETY", (await db.curriculumNode.count({ where: { curriculumVersionId: version1.id } })) === 3); pass("CROSS_VERSION_SAFETY", (await db.curriculumNode.count({ where: { curriculumVersionId: version2.id } })) === 0);
  await db.questionVersionCurriculumAlignment.deleteMany({ where: { questionVersionId: qv.id } }); await db.questionVersion.delete({ where: { id: qv.id } }); await db.question.delete({ where: { id: question.id } }); await db.curriculumStagedItem.deleteMany({ where: { jobId: { in: [job.id, changed.job.id] } } }); await db.curriculumEdge.deleteMany({ where: { source: { curriculumVersionId: version1.id } } }); await db.curriculumNode.deleteMany({ where: { curriculumVersionId: version1.id } }); await db.curriculumIngestionJob.deleteMany({ where: { sourceId: registered.source.id } }); await db.curriculumSource.delete({ where: { id: registered.source.id } }); await db.curriculumVersion.deleteMany({ where: { curriculumId: curriculum.id } }); await db.curriculum.delete({ where: { id: curriculum.id } }); await db.teacher.deleteMany({ where: { id: { in: [admin.id, teacher.id] } } }); await db.school.delete({ where: { id: school.id } }); pass("CLEANUP", (await db.school.count({ where: { code: { startsWith: marker } } })) === 0);
}
main().catch((error) => { console.error(error instanceof Error ? error.message : "F9C harness failed"); process.exitCode = 1; }).finally(() => db.$disconnect());
