import { getOpenRouterClient } from "../lib/ai/providers/openrouter";
import { MODEL_REGISTRY } from "../lib/ai/model-registry";
import { parseStrictJsonObject, classifyJsonShape } from "../lib/lessons/v2-json";
import { SHADOW_MODEL } from "../lib/lessons/v2-shadow";
import { buildStage3APrompt, buildStage3B1APrompt, buildStage3B1BPrompt, buildStage3B1CPrompt, buildStage3B2Prompt, buildStage4APrompt, buildStage4BPrompt, buildStage5Prompt } from "../lib/lessons/v2-prompts";
import { getQualificationFixture, qualificationInput, type QualificationStage } from "../lib/lessons/v2-qualification-fixtures";
import { validateStage3A, validateStage3B1A, validateStage3B1B, validateStage3B1C, validateStage3B2, validateStage4A, validateStage4B, validateStage5Generated } from "../lib/lessons/v2-validation";

const arg = (name: string, fallback: string) => { const inline = process.argv.find((x) => x.startsWith(`--${name}=`)); if (inline) return inline.slice(name.length + 3); const index = process.argv.indexOf(`--${name}`); return index >= 0 ? process.argv[index + 1] ?? fallback : fallback; };
const stage = arg("stage", "3A") as QualificationStage;
const model = arg("model", SHADOW_MODEL);
const known = MODEL_REGISTRY.filter((entry) => entry.provider === "openrouter").map((entry) => entry.id);
const fixture = getQualificationFixture(stage);
if (!fixture || !known.includes(model)) { console.log(JSON.stringify({ stage, requestedModel: model, status: "BLOCKED", validationErrors: [!fixture ? "Unsupported qualification stage" : "Model is not present in the OpenRouter registry"], liveRequestPerformed: false })); process.exit(0); }
const prompts: Record<QualificationStage, string> = { "3A": buildStage3APrompt(qualificationInput), "3B1A": buildStage3B1APrompt(qualificationInput), "3B1B": buildStage3B1BPrompt(qualificationInput), "3B1C": buildStage3B1CPrompt(qualificationInput), "3B2": buildStage3B2Prompt(qualificationInput), "4A": buildStage4APrompt(qualificationInput), "4B": buildStage4BPrompt(qualificationInput), "5": buildStage5Prompt(qualificationInput) };
const validate: Record<QualificationStage, (value: unknown) => { status: string; errors: { message: string }[] }> = { "3A": (value) => validateStage3A(value as never), "3B1A": validateStage3B1A, "3B1B": validateStage3B1B, "3B1C": validateStage3B1C, "3B2": validateStage3B2, "4A": validateStage4A, "4B": validateStage4B, "5": validateStage5Generated };
async function main() { const started = Date.now(); let raw: string | null = null; try { const completion = await getOpenRouterClient(model).chat.completions.create({ model, messages: [{ role: "user", content: prompts[stage] }], max_tokens: 1800, temperature: 0.2, response_format: { type: "json_object" } }, { signal: AbortSignal.timeout(90000) }); const choice = Array.isArray(completion.choices) ? completion.choices[0] : undefined; const content = choice && typeof choice === "object" ? (choice as { message?: { content?: unknown } }).message?.content : undefined; raw = typeof content === "string" ? content : null; if (!raw) throw new Error("Empty model response"); const payload = parseStrictJsonObject(raw); const result = validate[stage](payload); const wordCount = typeof (payload as Record<string, unknown>).content === "string" ? ((payload as Record<string, string>).content.trim().match(/\S+/g) ?? []).length : undefined; console.log(JSON.stringify({ stage, requestedModel: model, actualModel: completion.model, httpStatus: 200, status: result.status === "BLOCKED" ? "BLOCKED" : "PASS", latencyMs: Date.now() - started, validationErrors: result.errors.map((x) => x.message), responseCharacterCount: raw.length, wordCount, liveRequestPerformed: true })); } catch (error) { const e = error as { status?: number; message?: string }; const message = e.message ?? "Qualification request failed"; console.log(JSON.stringify({ stage, requestedModel: model, httpStatus: e.status, status: "BLOCKED", latencyMs: Date.now() - started, validationErrors: [message], ...(raw ? { responseCharacterCount: raw.length, shapeDiagnostic: classifyJsonShape(raw) } : {}), liveRequestPerformed: true })); } }
void main();
