import assert from "node:assert/strict";
import { assembleLesson, renderLessonMarkdown } from "../lib/lessons/v2-assembly";
import { detectLessonContent, LESSON_V2_CONTRACT_VERSION, type LessonStages } from "../lib/lessons/v2-contract";
import { classifyShadowError, extractCompletionContent, stopReasonForStage } from "../lib/lessons/v2-shadow";
import { assembleTeachingContentChunks, classifyStage1AShape, classifyStage1BShape, mergeStage2, mergeStage3, mergeStage3B1Substages, mergeStage3Substages, roadmapLimitForPeriods, validateLessonContract, validateStage1A, validateStage1B, validateStage1C, validateStage2A, validateStage2A1, validateStage2B, validateStage3A, validateStage3B, validateStage3B1, validateStage3B1A, validateStage3B1B, validateStage3B1C, validateStage3B2, validateTeachingContentChunk, validateTeachingContentChunkContent } from "../lib/lessons/v2-validation";
import { buildStage3B2Prompt, buildStage4Prompt } from "../lib/lessons/v2-prompts";
import { classifyJsonShape, parseStrictJsonObject } from "../lib/lessons/v2-json";
import { deriveStemDeterministically } from "../lib/lessons/v2-stem";
import { serializeShadowStageResults, type ShadowStageResult } from "../lib/lessons/v2-shadow";

const metadata = { subject: "Mathematics", classLevel: "SS1", topic: "Quadratic Equations", term: "FIRST", week: 1, periods: 1, durationMinutes: 45, curriculumLabels: ["NERDC"] };
const provenance = { origin: "AI_GENERATED" as const, sourceLocations: [], extracted: false, generated: true, aiTransformedSource: false, teacherEditState: "NOT_REVIEWED" as const, provider: "test", requestedModel: "test", actualModel: "test", generatedAt: new Date(0).toISOString(), templateVersion: LESSON_V2_CONTRACT_VERSION, curriculumContextUsed: false, textbookContextUsed: false, stages: {} };
const common = { metadata, provenance };
const stage1A = { ...common, stage: "1A" as const, curriculumCore: { objectives: ["Solve equations"], learningOutcomes: ["Solve"], bloomsDistribution: {} }, vocabulary: [{ term: "root", definition: "solution", analogy: "market balance" }], symbolsNotation: "x²" };
const stage1B = { ...common, stage: "1B" as const, entryBehaviour: [{ topic: "Algebra" }], diagnosticQuestions: ["What is x?"] };
const stage1C = { ...common, stage: "1C" as const, roadmap: [{ title: "Factorisation", status: "COVERED" as const }, { title: "Formula", status: "NEXT" as const }] };
assert.equal(validateStage1A(stage1A).status, "PASS");
assert.equal(validateStage1B(stage1B).status, "PASS");
assert.equal(validateStage1C(stage1C).status, "PASS");
assert.equal(validateStage1C({ ...stage1C, roadmap: [] }).status, "BLOCKED");
assert.equal(validateStage1C({ ...stage1C, roadmap: [{ title: "Factorisation", status: "NEXT" }, { title: "factorisation", status: "FUTURE" }] }).status, "BLOCKED");
assert.equal(roadmapLimitForPeriods(1), 3); assert.equal(roadmapLimitForPeriods(2), 5); assert.equal(roadmapLimitForPeriods(10), 8); const maxRoadmap = Array.from({ length: roadmapLimitForPeriods(1) }, (_, index) => ({ title: `Step ${index + 1}`, status: "NEXT" as const })); assert.equal(validateStage1C({ ...stage1C, roadmap: maxRoadmap }).status, "PASS"); assert.equal(validateStage1C({ ...stage1C, roadmap: [...maxRoadmap, { title: "Extra", status: "FUTURE" as const }] }, roadmapLimitForPeriods(1)).status, "BLOCKED");
const shape1a = classifyStage1AShape({ curriculumCore: { objectives: [], learningOutcomes: [], bloomsDistribution: {} }, vocabulary: [{ word: "x", meaning: "y" }], symbolsNotation: ["x²"], extra: true }); assert.deepEqual(shape1a.fields.vocabulary?.itemTypes, ["object"]); assert.deepEqual(shape1a.fields.vocabulary?.objectKeys, ["word", "meaning"]); assert.equal(shape1a.fields.symbolsNotation?.type, "array"); assert.deepEqual(shape1a.unexpectedKeys, ["extra"]);
assert.equal(validateStage1B({ entryBehaviour: [{ topic: "Algebra" }], diagnosticQuestions: ["What is x?"] }).status, "PASS"); for (const bad of [null, "bad", {}, { entryBehaviour: [], diagnosticQuestions: null }, { entryBehaviour: [], diagnosticQuestions: "question" }, { entryBehaviour: [], diagnosticQuestions: [{}] }]) assert.doesNotThrow(() => validateStage1B(bad as never)); assert.equal(validateStage1B({ entryBehaviour: [], diagnosticQuestions: ["same", "same"] }).status, "BLOCKED"); const shape1b = classifyStage1BShape({ entryBehaviour: "bad", diagnosticQuestions: [{ prompt: "x" }], extra: 1 }); assert.equal(shape1b.fields.entryBehaviour.type, "string"); assert.equal(shape1b.fields.diagnosticQuestions.count, 1); assert.deepEqual(shape1b.fields.diagnosticQuestions.itemTypes, ["object"]); assert.deepEqual(shape1b.unexpectedKeys, ["extra"]);
assert.equal(stopReasonForStage("1A"), "STAGE_1_FAILURE"); assert.equal(stopReasonForStage(1), "STAGE_1_FAILURE"); assert.notEqual(stopReasonForStage("1A"), "STAGE_3A_FAILURE"); assert.equal(stopReasonForStage("3A"), "STAGE_3A_FAILURE"); assert.equal(stopReasonForStage("2A1"), "STAGE_2A1_FAILURE"); assert.equal(stopReasonForStage("2A_CONTENT"), "ROADMAP_CHUNK_FAILURE"); assert.equal(stopReasonForStage(4), "STAGE_4_FAILURE"); assert.equal(stopReasonForStage(5), "STAGE_5_FAILURE");
assert.equal(validateStage1A({ curriculumCore: { objectives: null, learningOutcomes: "bad", bloomsDistribution: [] }, vocabulary: "bad", symbolsNotation: null } as never).status, "BLOCKED"); assert.equal(classifyShadowError("1A", "((intermediate value) ?? []) is not iterable"), "LOCAL_STAGE_PROCESSING_FAILURE");
assert.equal(extractCompletionContent({}), null); assert.equal(extractCompletionContent({ choices: null }), null); assert.equal(extractCompletionContent({ choices: [] }), null); assert.equal(extractCompletionContent({ choices: [{ message: { content: "ok" } }] }), "ok");
const chunkText = Array.from({ length: 200 }, (_, i) => `word${i}`).join(" "); assert.equal(validateTeachingContentChunkContent({ content: chunkText }).status, "PASS"); assert.equal(validateTeachingContentChunkContent({ content: "short" }).status, "BLOCKED"); assert.equal(validateTeachingContentChunkContent({ content: `${chunkText} ${Array.from({ length: 500 }, () => "extra").join(" ")}` }).status, "BLOCKED"); assert.equal(validateTeachingContentChunkContent({ content: `${chunkText} [placeholder]` }).status, "BLOCKED"); const authoritativeChunk = { ...common, stage: "2A_CONTENT" as const, roadmapId: "roadmap-1", roadmapIndex: 0, title: "Factorisation", content: chunkText }; assert.equal(validateTeachingContentChunk(authoritativeChunk, [{ title: "Factorisation", status: "COVERED" }], 0).status, "PASS"); assert.equal(assembleTeachingContentChunks([authoritativeChunk], [{ title: "Factorisation", status: "COVERED" }]).teachingContent?.startsWith("## Factorisation"), true);
const stages: LessonStages = [
  { ...common, stage: 1, curriculum: { objectives: ["Solve equations"], learningOutcomes: ["Solve"], bloomsDistribution: {}, entryBehaviour: [{ topic: "Algebra" }], diagnosticQuestions: ["What is x?"], roadmap: [{ title: "Quadratics", status: "COVERED" }, { title: "Graphs", status: "NEXT" }, { title: "Complex roots", status: "FUTURE" }] }, vocabulary: [{ term: "root", definition: "solution", analogy: "market balance" }], symbolsNotation: "x" },
  { ...common, stage: 2, materials: ["Board"], hook: "Hook", history: "History", teachingContent: "Content", stem: { sourceRepresentation: "$x^2$", conversionWarnings: [] } },
  { ...common, stage: 3, workedExamples: [1, 2, 3, 4, 5].map((level) => ({ level: level as 1|2|3|4|5, question: `Q${level}`, solution: `S${level}` })), misconceptions: "Mistakes", activities: "Activities", differentiation: "Struggling, average, advanced", formativeAssessment: "Check", higherOrderQuestions: "Why?" },
  { ...common, stage: 4, applications: "Banking", examinationGuidance: "Exam style", examinationItems: [{ sourceStatus: "GENERATED_EXAM_STYLE", examStyle: "WAEC", question: "Q", answer: "A" }] },
  { ...common, stage: 5, classExercise: ["Exercise"], boardSummary: ["Summary"], comingNext: "Graphs", homework: "Homework", studentSummary: "Revision", teacherReflection: { template: true, prompts: ["What went well?"], completed: false } },
];
const assembled = assembleLesson({ 1: stages[0], 2: stages[1], 3: stages[2], 4: stages[3], 5: stages[4] });
assert.equal(assembled.validation.status, "PASS");
assert.ok(assembled.contract);
assert.match(renderLessonMarkdown(assembled.contract!), /SECTION 24/);
assert.equal(detectLessonContent({ markdown: "legacy" }), "LEGACY_UNSTRUCTURED");
assert.equal(detectLessonContent({ contractVersion: LESSON_V2_CONTRACT_VERSION, sections: {} }), "V2_STRUCTURED");
assert.equal(validateLessonContract({ ...assembled.contract!, workedExamples: stages[2].workedExamples.slice(0, 4) }, metadata).status, "BLOCKED");
assert.equal(validateLessonContract({ ...assembled.contract!, assessment: { ...assembled.contract!.assessment, examinationItems: [{ sourceStatus: "VERIFIED_RETRIEVED_SOURCE", examStyle: "WAEC", question: "Q", answer: "A" }] } }, metadata).status, "BLOCKED");
assert.equal(validateLessonContract({ ...assembled.contract!, provenance: { ...assembled.contract!.provenance, origin: "MANUAL", provider: undefined, requestedModel: undefined, generated: false } }, metadata).status, "PASS");
assert.match(buildStage4Prompt({ metadata }), /GENERATED_EXAM_STYLE/);
assert.equal(validateLessonContract({ ...assembled.contract!, provenance: { ...assembled.contract!.provenance, origin: "BOOK_EXTRACTION", sourceLocations: [] } }, metadata).status, "BLOCKED");
assert.equal(validateLessonContract({ ...assembled.contract!, provenance: { ...assembled.contract!.provenance, origin: "BOOK_EXTRACTION", sourceLocations: [{ documentId: "book-1", page: 3 }], generated: false, extracted: true, provider: undefined, requestedModel: undefined } }, metadata).status, "PASS");
assert.equal(assembled.contract!.stem.sourceRepresentation, "$x^2$");
assert.equal(buildStage4Prompt({ metadata, source: { mode: "EXTRACT_FROM_SOURCE", excerpts: ["Source equation"], locations: [{ documentId: "doc-1", page: 1 }] } }).includes("VERIFIED_RETRIEVED_SOURCE"), true);
const pasted = "Solve $x^2 - 4 = 0$; use √x and H₂O, matrix [1 0; 0 1]."; assert.equal(deriveStemDeterministically({ origin: "PASTE", sourceRepresentation: pasted, warnings: ["OMML retained"] }).sourceRepresentation, pasted); const generatedStem = deriveStemDeterministically({ origin: "AI_GENERATED" }, "Solve $x^2 - 4 = 0$ with 3/4 and v = u + at"); assert.match(generatedStem.sourceRepresentation, /\$x\^2 - 4 = 0\$/); assert.equal(generatedStem.conversionWarnings.length, 0); const grounded = deriveStemDeterministically({ origin: "AI_GROUNDED_IN_SOURCE", sourceRepresentation: "\\frac{3}{4}", warnings: ["Source evidence retained"] }, "Generated explanation"); assert.equal(grounded.sourceRepresentation, "\\frac{3}{4}"); assert.deepEqual(grounded.conversionWarnings, ["Source evidence retained"]);
const stage3a = { ...common, stage: "3A" as const, workedExamples: stages[2].workedExamples };
const stage3b = { ...common, stage: "3B" as const, misconceptions: "Mistakes", activities: "Activities", differentiation: "Differentiation", formativeAssessment: "Check", higherOrderQuestions: "Why?" };
const stage2a = { ...common, stage: "2A" as const, materials: ["Board"], hook: "Hook", history: "History", teachingContent: "Content" }; const stage2b = { ...common, stage: "2B" as const, stem: { sourceRepresentation: "$x^2$", conversionWarnings: [] } }; assert.equal(validateStage2A(stage2a).status, "PASS"); assert.equal(validateStage2A({ ...stage2a, hook: "" }).status, "BLOCKED"); assert.equal(validateStage2B(stage2b).status, "PASS"); assert.equal(validateStage2B({ ...stage2b, stem: { sourceRepresentation: "", conversionWarnings: [] } }).status, "BLOCKED"); const mergedStage2 = mergeStage2(stage2a, stage2b); assert.equal(mergedStage2.stage, 2); assert.equal(mergedStage2.stem.sourceRepresentation, "$x^2$");
const stage2a1 = { ...common, stage: "2A1" as const, materials: ["Board"], hook: "Hook", history: null }; assert.equal(validateStage2A1(stage2a1).status, "PASS"); assert.equal(validateStage2A1({ ...stage2a1, hook: undefined } as unknown as typeof stage2a1).status, "BLOCKED"); assert.equal(validateStage2A1({ ...stage2a1, history: "" }).status, "BLOCKED"); assert.equal(validateStage2A1({ ...stage2a1, history: "[placeholder]" }).status, "BLOCKED");
assert.equal(validateStage3A(stage3a).status, "PASS"); assert.equal(validateStage3A({ ...stage3a, workedExamples: stage3a.workedExamples.slice(0, 4) }).status, "BLOCKED"); assert.equal(validateStage3A({ ...stage3a, workedExamples: stage3a.workedExamples.map((x) => ({ ...x, level: 1 })) }).status, "BLOCKED"); assert.equal(validateStage3A({ ...stage3a, workedExamples: [...stage3a.workedExamples, { level: 5, question: "Q6", solution: "S6" }] }).status, "BLOCKED"); assert.equal(validateStage3B(stage3b).status, "PASS"); assert.equal(validateStage3B({ ...stage3b, activities: "" }).status, "BLOCKED"); const merged = mergeStage3(stage3a, stage3b); assert.equal(merged.stage, 3); assert.equal(merged.workedExamples.length, 5); assert.equal(merged.differentiation, "Differentiation");
assert.equal(validateStage3B2({ formativeAssessment: "Check", higherOrderQuestions: "Why?" }).status, "PASS"); for (const bad of [null, {}, { formativeAssessment: "Check" }, { higherOrderQuestions: "Why?" }, { formativeAssessment: [], higherOrderQuestions: {} }, { formativeAssessment: "[placeholder]", higherOrderQuestions: "Why?" }, { wrapper: { formativeAssessment: "x", higherOrderQuestions: "y" } }]) assert.doesNotThrow(() => validateStage3B2(bad as never)); assert.equal(buildStage3B2Prompt({ metadata }).includes('"formativeAssessment":"string"'), true);
const stage3b1 = { ...common, stage: "3B1" as const, misconceptions: "Mistakes", activities: "Activities", differentiation: "Differentiation" }; const stage3b2 = { ...common, stage: "3B2" as const, formativeAssessment: "Check", higherOrderQuestions: "Why?" }; assert.equal(validateStage3B1(stage3b1).status, "PASS"); assert.equal(validateStage3B1({ ...stage3b1, misconceptions: "" }).status, "BLOCKED"); assert.equal(validateStage3B1({ ...stage3b1, activities: "" }).status, "BLOCKED"); assert.equal(validateStage3B1({ ...stage3b1, differentiation: "" }).status, "BLOCKED"); assert.equal(validateStage3B2(stage3b2).status, "PASS"); assert.equal(validateStage3B2({ ...stage3b2, formativeAssessment: "" }).status, "BLOCKED"); assert.equal(validateStage3B2({ ...stage3b2, higherOrderQuestions: "" }).status, "BLOCKED"); const splitMerged = mergeStage3Substages(stage3a, stage3b1, stage3b2); assert.equal(validateLessonContract({ ...assembled.contract!, instruction: { ...assembled.contract!.instruction, misconceptions: splitMerged.misconceptions, activities: splitMerged.activities, differentiation: splitMerged.differentiation, formativeAssessment: splitMerged.formativeAssessment, higherOrderQuestions: splitMerged.higherOrderQuestions }, workedExamples: splitMerged.workedExamples }, metadata).status, "PASS");
const b1a = { ...common, stage: "3B1A" as const, misconceptions: "Mistakes" }; const b1b = { ...common, stage: "3B1B" as const, activities: "Activities" }; const b1c = { ...common, stage: "3B1C" as const, differentiation: "Differentiation" }; assert.equal(validateStage3B1A(b1a).status, "PASS"); assert.equal(validateStage3B1B(b1b).status, "PASS"); assert.equal(validateStage3B1C(b1c).status, "PASS"); assert.equal(validateStage3B1A({ misconceptions: "[placeholder]" }).status, "BLOCKED"); assert.equal(validateStage3B1B({ activities: 3 }).status, "BLOCKED"); assert.equal(validateStage3B1C({}).status, "BLOCKED"); const mergedB1 = mergeStage3B1Substages(b1a, b1b, b1c); assert.equal(validateStage3B1(mergedB1).status, "PASS");
assert.deepEqual(parseStrictJsonObject('{"ok":true}'), { ok: true });
assert.deepEqual(parseStrictJsonObject(' \n```json\n{"ok":true}\n``` \n'), { ok: true });
for (const invalid of ['prose {"ok":true}', '{"ok":true} prose', 'prose\n```json\n{"ok":true}\n```', '```json\n{"ok":true}\n```\nprose', '```json\n{"ok":true}\n```\n```json\n{"ok":false}\n```', '{"ok":', '```json\n{"ok":true}', '```text\n{"ok":true}\n```', '{"a":1}{"b":2}']) assert.throws(() => parseStrictJsonObject(invalid));
const shape = classifyJsonShape("\n```json\n{\"ok\":true}\n```");
assert.equal(shape.beginsWithCodeFence, true); assert.equal(shape.openingFenceLanguage, "json"); assert.equal(shape.closingFencePresent, true); assert.equal(shape.numberOfCodeFences, 2); assert.equal(shape.responseCharacterCount, 24); assert.equal(shape.firstNonWhitespaceToken, "CODE_FENCE"); assert.equal(shape.lastNonWhitespaceToken, "CODE_FENCE_END");
const malformedStage: ShadowStageResult = { stage: 1, status: "BLOCKED", validationErrors: ["Stage output must be a raw JSON object or one JSON code fence"], shapeDiagnostic: classifyJsonShape("prose before JSON") };
const serialized = serializeShadowStageResults([malformedStage]); assert.deepEqual((JSON.parse(JSON.stringify({ stages: serialized })).stages[0] as ShadowStageResult).shapeDiagnostic, malformedStage.shapeDiagnostic);
console.log("Lesson V2 deterministic verification: PASS");
