export interface LatexSymbol {
  latex: string;
  label: string;
  description: string;
}

export interface SymbolCategory {
  id: string;
  name: string;
  symbols: LatexSymbol[];
}

// ── Greek Letters (Lowercase) ─────────────────────────────────────────────────
const GREEK_LOWER: LatexSymbol[] = [
  { latex: "\\alpha", label: "α", description: "alpha" },
  { latex: "\\beta", label: "β", description: "beta" },
  { latex: "\\gamma", label: "γ", description: "gamma" },
  { latex: "\\delta", label: "δ", description: "delta" },
  { latex: "\\epsilon", label: "ϵ", description: "epsilon" },
  { latex: "\\varepsilon", label: "ε", description: "varepsilon" },
  { latex: "\\zeta", label: "ζ", description: "zeta" },
  { latex: "\\eta", label: "η", description: "eta" },
  { latex: "\\theta", label: "θ", description: "theta" },
  { latex: "\\vartheta", label: "ϑ", description: "vartheta" },
  { latex: "\\iota", label: "ι", description: "iota" },
  { latex: "\\kappa", label: "κ", description: "kappa" },
  { latex: "\\varkappa", label: "ϰ", description: "varkappa" },
  { latex: "\\lambda", label: "λ", description: "lambda" },
  { latex: "\\mu", label: "μ", description: "mu" },
  { latex: "\\nu", label: "ν", description: "nu" },
  { latex: "\\xi", label: "ξ", description: "xi" },
  { latex: "\\pi", label: "π", description: "pi" },
  { latex: "\\varpi", label: "ϖ", description: "varpi" },
  { latex: "\\rho", label: "ρ", description: "rho" },
  { latex: "\\varrho", label: "ϱ", description: "varrho" },
  { latex: "\\sigma", label: "σ", description: "sigma" },
  { latex: "\\varsigma", label: "ς", description: "varsigma" },
  { latex: "\\tau", label: "τ", description: "tau" },
  { latex: "\\upsilon", label: "υ", description: "upsilon" },
  { latex: "\\phi", label: "ϕ", description: "phi" },
  { latex: "\\varphi", label: "φ", description: "varphi" },
  { latex: "\\chi", label: "χ", description: "chi" },
  { latex: "\\psi", label: "ψ", description: "psi" },
  { latex: "\\omega", label: "ω", description: "omega" },
  { latex: "\\digamma", label: "ϝ", description: "digamma" },
];

// ── Greek Letters (Uppercase) ─────────────────────────────────────────────────
const GREEK_UPPER: LatexSymbol[] = [
  { latex: "\\Alpha", label: "Α", description: "Alpha" },
  { latex: "\\Beta", label: "Β", description: "Beta" },
  { latex: "\\Gamma", label: "Γ", description: "Gamma" },
  { latex: "\\Delta", label: "Δ", description: "Delta" },
  { latex: "\\Epsilon", label: "Ε", description: "Epsilon" },
  { latex: "\\Zeta", label: "Ζ", description: "Zeta" },
  { latex: "\\Eta", label: "Η", description: "Eta" },
  { latex: "\\Theta", label: "Θ", description: "Theta" },
  { latex: "\\Iota", label: "Ι", description: "Iota" },
  { latex: "\\Kappa", label: "Κ", description: "Kappa" },
  { latex: "\\Lambda", label: "Λ", description: "Lambda" },
  { latex: "\\Mu", label: "Μ", description: "Mu" },
  { latex: "\\Nu", label: "Ν", description: "Nu" },
  { latex: "\\Xi", label: "Ξ", description: "Xi" },
  { latex: "\\Pi", label: "Π", description: "Pi" },
  { latex: "\\Rho", label: "Ρ", description: "Rho" },
  { latex: "\\Sigma", label: "Σ", description: "Sigma" },
  { latex: "\\Tau", label: "Τ", description: "Tau" },
  { latex: "\\Upsilon", label: "Υ", description: "Upsilon" },
  { latex: "\\Phi", label: "Φ", description: "Phi" },
  { latex: "\\Chi", label: "Χ", description: "Chi" },
  { latex: "\\Psi", label: "Ψ", description: "Psi" },
  { latex: "\\Omega", label: "Ω", description: "Omega" },
];

// ── Operators ─────────────────────────────────────────────────────────────────
const OPERATORS: LatexSymbol[] = [
  { latex: "+", label: "+", description: "plus" },
  { latex: "-", label: "−", description: "minus" },
  { latex: "\\times", label: "×", description: "times/multiply" },
  { latex: "\\div", label: "÷", description: "divide" },
  { latex: "\\pm", label: "±", description: "plus or minus" },
  { latex: "\\mp", label: "∓", description: "minus or plus" },
  { latex: "\\cdot", label: "·", description: "center dot multiply" },
  { latex: "\\ast", label: "∗", description: "asterisk" },
  { latex: "\\star", label: "⋆", description: "star" },
  { latex: "\\circ", label: "∘", description: "composition/circle" },
  { latex: "\\bullet", label: "•", description: "bullet" },
  { latex: "\\oplus", label: "⊕", description: "circled plus" },
  { latex: "\\ominus", label: "⊖", description: "circled minus" },
  { latex: "\\otimes", label: "⊗", description: "circled times / tensor" },
  { latex: "\\oslash", label: "⊘", description: "circled slash" },
  { latex: "\\odot", label: "⊙", description: "circled dot" },
  { latex: "\\bigcirc", label: "○", description: "big circle" },
  { latex: "\\dagger", label: "†", description: "dagger" },
  { latex: "\\ddagger", label: "‡", description: "double dagger" },
  { latex: "\\amalg", label: "⨿", description: "amalgamation" },
  { latex: "\\cap", label: "∩", description: "intersection" },
  { latex: "\\cup", label: "∪", description: "union" },
  { latex: "\\sqcap", label: "⊓", description: "square cap" },
  { latex: "\\sqcup", label: "⊔", description: "square cup" },
  { latex: "\\vee", label: "∨", description: "logical or / vee" },
  { latex: "\\wedge", label: "∧", description: "logical and / wedge" },
  { latex: "\\setminus", label: "∖", description: "set minus" },
  { latex: "\\wr", label: "≀", description: "wreath product" },
  { latex: "\\triangleleft", label: "◁", description: "triangle left" },
  { latex: "\\triangleright", label: "▷", description: "triangle right" },
  { latex: "\\lhd", label: "⊲", description: "left normal subgroup" },
  { latex: "\\rhd", label: "⊳", description: "right normal subgroup" },
  { latex: "\\unlhd", label: "⊴", description: "normal subgroup or equal" },
  { latex: "\\unrhd", label: "⊵", description: "normal subgroup or equal (right)" },
  { latex: "\\bigtriangleup", label: "△", description: "big triangle up" },
  { latex: "\\bigtriangledown", label: "▽", description: "big triangle down" },
  { latex: "\\barwedge", label: "⊼", description: "nand" },
  { latex: "\\veebar", label: "⊻", description: "xor" },
  { latex: "\\doublebarwedge", label: "⩞", description: "double bar wedge" },
  { latex: "\\boxplus", label: "⊞", description: "box plus" },
  { latex: "\\boxminus", label: "⊟", description: "box minus" },
  { latex: "\\boxtimes", label: "⊠", description: "box times" },
  { latex: "\\boxdot", label: "⊡", description: "box dot" },
  { latex: "\\divideontimes", label: "⋇", description: "divide on times" },
  { latex: "\\ltimes", label: "⋉", description: "left semidirect product" },
  { latex: "\\rtimes", label: "⋊", description: "right semidirect product" },
  { latex: "\\leftthreetimes", label: "⋋", description: "left three times" },
  { latex: "\\rightthreetimes", label: "⋌", description: "right three times" },
  { latex: "\\intercal", label: "⊺", description: "intercal" },
];

// ── Relations ─────────────────────────────────────────────────────────────────
const RELATIONS: LatexSymbol[] = [
  { latex: "=", label: "=", description: "equals" },
  { latex: "\\neq", label: "≠", description: "not equal" },
  { latex: "<", label: "<", description: "less than" },
  { latex: ">", label: ">", description: "greater than" },
  { latex: "\\leq", label: "≤", description: "less than or equal" },
  { latex: "\\geq", label: "≥", description: "greater than or equal" },
  { latex: "\\ll", label: "≪", description: "much less than" },
  { latex: "\\gg", label: "≫", description: "much greater than" },
  { latex: "\\equiv", label: "≡", description: "equivalent / identical" },
  { latex: "\\approx", label: "≈", description: "approximately equal" },
  { latex: "\\cong", label: "≅", description: "congruent" },
  { latex: "\\sim", label: "∼", description: "similar / tilde" },
  { latex: "\\simeq", label: "≃", description: "similar or equal" },
  { latex: "\\propto", label: "∝", description: "proportional to" },
  { latex: "\\asymp", label: "≍", description: "asymptotically equal" },
  { latex: "\\doteq", label: "≐", description: "dot equals" },
  { latex: "\\triangleq", label: "≜", description: "defined equal" },
  { latex: "\\perp", label: "⊥", description: "perpendicular" },
  { latex: "\\parallel", label: "∥", description: "parallel" },
  { latex: "\\mid", label: "|", description: "divides / such that" },
  { latex: "\\nmid", label: "∤", description: "does not divide" },
  { latex: "\\vdash", label: "⊢", description: "proves / turnstile" },
  { latex: "\\dashv", label: "⊣", description: "reverse turnstile" },
  { latex: "\\models", label: "⊨", description: "models / satisfies" },
  { latex: "\\prec", label: "≺", description: "precedes" },
  { latex: "\\succ", label: "≻", description: "succeeds" },
  { latex: "\\preceq", label: "⪯", description: "precedes or equal" },
  { latex: "\\succeq", label: "⪰", description: "succeeds or equal" },
  { latex: "\\subset", label: "⊂", description: "subset" },
  { latex: "\\supset", label: "⊃", description: "superset" },
  { latex: "\\subseteq", label: "⊆", description: "subset or equal" },
  { latex: "\\supseteq", label: "⊇", description: "superset or equal" },
  { latex: "\\subsetneq", label: "⊊", description: "proper subset" },
  { latex: "\\supsetneq", label: "⊋", description: "proper superset" },
  { latex: "\\sqsubset", label: "⊏", description: "square subset" },
  { latex: "\\sqsupset", label: "⊐", description: "square superset" },
  { latex: "\\sqsubseteq", label: "⊑", description: "square subset or equal" },
  { latex: "\\sqsupseteq", label: "⊒", description: "square superset or equal" },
  { latex: "\\in", label: "∈", description: "element of" },
  { latex: "\\notin", label: "∉", description: "not element of" },
  { latex: "\\ni", label: "∋", description: "contains element" },
  { latex: "\\leqslant", label: "⩽", description: "less than or slant equal" },
  { latex: "\\geqslant", label: "⩾", description: "greater than or slant equal" },
  { latex: "\\eqslantless", label: "⪕", description: "equal or slant less" },
  { latex: "\\eqslantgtr", label: "⪖", description: "equal or slant greater" },
  { latex: "\\lesssim", label: "≲", description: "less or similar" },
  { latex: "\\gtrsim", label: "≳", description: "greater or similar" },
  { latex: "\\lessapprox", label: "⪅", description: "less or approx" },
  { latex: "\\gtrapprox", label: "⪆", description: "greater or approx" },
  { latex: "\\lll", label: "⋘", description: "triple less than" },
  { latex: "\\ggg", label: "⋙", description: "triple greater than" },
];

// ── Arrows ───────────────────────────────────────────────────────────────────
const ARROWS: LatexSymbol[] = [
  { latex: "\\rightarrow", label: "→", description: "right arrow" },
  { latex: "\\leftarrow", label: "←", description: "left arrow" },
  { latex: "\\uparrow", label: "↑", description: "up arrow" },
  { latex: "\\downarrow", label: "↓", description: "down arrow" },
  { latex: "\\leftrightarrow", label: "↔", description: "left-right arrow" },
  { latex: "\\updownarrow", label: "↕", description: "up-down arrow" },
  { latex: "\\Rightarrow", label: "⇒", description: "double right arrow / implies" },
  { latex: "\\Leftarrow", label: "⇐", description: "double left arrow" },
  { latex: "\\Uparrow", label: "⇑", description: "double up arrow" },
  { latex: "\\Downarrow", label: "⇓", description: "double down arrow" },
  { latex: "\\Leftrightarrow", label: "⇔", description: "double left-right / iff" },
  { latex: "\\Updownarrow", label: "⇕", description: "double up-down arrow" },
  { latex: "\\nearrow", label: "↗", description: "north-east arrow" },
  { latex: "\\searrow", label: "↘", description: "south-east arrow" },
  { latex: "\\swarrow", label: "↙", description: "south-west arrow" },
  { latex: "\\nwarrow", label: "↖", description: "north-west arrow" },
  { latex: "\\mapsto", label: "↦", description: "maps to" },
  { latex: "\\longmapsto", label: "⟼", description: "long maps to" },
  { latex: "\\longrightarrow", label: "⟶", description: "long right arrow" },
  { latex: "\\longleftarrow", label: "⟵", description: "long left arrow" },
  { latex: "\\longleftrightarrow", label: "⟷", description: "long left-right arrow" },
  { latex: "\\Longrightarrow", label: "⟹", description: "long double right arrow" },
  { latex: "\\Longleftarrow", label: "⟸", description: "long double left arrow" },
  { latex: "\\Longleftrightarrow", label: "⟺", description: "long double left-right" },
  { latex: "\\hookrightarrow", label: "↪", description: "hook right arrow" },
  { latex: "\\hookleftarrow", label: "↩", description: "hook left arrow" },
  { latex: "\\rightharpoonup", label: "⇀", description: "right harpoon up" },
  { latex: "\\rightharpoondown", label: "⇁", description: "right harpoon down" },
  { latex: "\\leftharpoonup", label: "↼", description: "left harpoon up" },
  { latex: "\\leftharpoondown", label: "↽", description: "left harpoon down" },
  { latex: "\\rightleftharpoons", label: "⇌", description: "equilibrium arrows" },
  { latex: "\\leftrightharpoons", label: "⇋", description: "left-right harpoons" },
  { latex: "\\curvearrowleft", label: "↶", description: "curve arrow left" },
  { latex: "\\curvearrowright", label: "↷", description: "curve arrow right" },
  { latex: "\\circlearrowleft", label: "↺", description: "circle arrow left" },
  { latex: "\\circlearrowright", label: "↻", description: "circle arrow right" },
  { latex: "\\twoheadrightarrow", label: "↠", description: "two-head right arrow (surjection)" },
  { latex: "\\twoheadleftarrow", label: "↞", description: "two-head left arrow" },
  { latex: "\\rightarrowtail", label: "↣", description: "right arrow tail (injection)" },
  { latex: "\\leftarrowtail", label: "↢", description: "left arrow tail" },
  { latex: "\\to", label: "→", description: "to (right arrow alias)" },
  { latex: "\\gets", label: "←", description: "gets (left arrow alias)" },
  { latex: "\\leadsto", label: "⤳", description: "leads to" },
  { latex: "\\dashrightarrow", label: "⇢", description: "dashed right arrow" },
  { latex: "\\dashleftarrow", label: "⇠", description: "dashed left arrow" },
  { latex: "\\multimap", label: "⊸", description: "linear implication" },
  { latex: "\\nrightarrow", label: "↛", description: "not right arrow" },
  { latex: "\\nleftarrow", label: "↚", description: "not left arrow" },
  { latex: "\\nRightarrow", label: "⇏", description: "not double right arrow" },
  { latex: "\\nLeftarrow", label: "⇍", description: "not double left arrow" },
  { latex: "\\nLeftrightarrow", label: "⇎", description: "not left-right double" },
];

// ── Sets & Logic ──────────────────────────────────────────────────────────────
const SETS_LOGIC: LatexSymbol[] = [
  { latex: "\\emptyset", label: "∅", description: "empty set" },
  { latex: "\\varnothing", label: "∅", description: "empty set (var)" },
  { latex: "\\mathbb{N}", label: "ℕ", description: "natural numbers" },
  { latex: "\\mathbb{Z}", label: "ℤ", description: "integers" },
  { latex: "\\mathbb{Q}", label: "ℚ", description: "rational numbers" },
  { latex: "\\mathbb{R}", label: "ℝ", description: "real numbers" },
  { latex: "\\mathbb{C}", label: "ℂ", description: "complex numbers" },
  { latex: "\\mathbb{P}", label: "ℙ", description: "primes / probability" },
  { latex: "\\mathbb{F}", label: "𝔽", description: "field" },
  { latex: "\\mathbb{H}", label: "ℍ", description: "quaternions" },
  { latex: "\\forall", label: "∀", description: "for all" },
  { latex: "\\exists", label: "∃", description: "there exists" },
  { latex: "\\nexists", label: "∄", description: "there does not exist" },
  { latex: "\\neg", label: "¬", description: "negation / not" },
  { latex: "\\land", label: "∧", description: "logical and" },
  { latex: "\\lor", label: "∨", description: "logical or" },
  { latex: "\\Rightarrow", label: "⇒", description: "implies" },
  { latex: "\\Leftrightarrow", label: "⇔", description: "if and only if" },
  { latex: "\\top", label: "⊤", description: "top / tautology" },
  { latex: "\\bot", label: "⊥", description: "bottom / contradiction" },
  { latex: "\\therefore", label: "∴", description: "therefore" },
  { latex: "\\because", label: "∵", description: "because" },
  { latex: "\\complement", label: "∁", description: "complement" },
  { latex: "\\setminus", label: "∖", description: "set difference" },
  { latex: "\\triangle", label: "△", description: "symmetric difference" },
  { latex: "\\bigcap", label: "⋂", description: "big intersection" },
  { latex: "\\bigcup", label: "⋃", description: "big union" },
  { latex: "\\bigsqcup", label: "⨆", description: "big square union" },
  { latex: "\\biguplus", label: "⨄", description: "big union plus" },
  { latex: "\\bigvee", label: "⋁", description: "big logical or" },
  { latex: "\\bigwedge", label: "⋀", description: "big logical and" },
  { latex: "\\iff", label: "⟺", description: "if and only if (long)" },
  { latex: "\\implies", label: "⟹", description: "implies (long)" },
  { latex: "\\vdash", label: "⊢", description: "proves" },
  { latex: "\\models", label: "⊨", description: "satisfies / models" },
  { latex: "\\lnot", label: "¬", description: "logical not" },
];

// ── Calculus & Analysis ───────────────────────────────────────────────────────
const CALCULUS: LatexSymbol[] = [
  { latex: "\\int", label: "∫", description: "integral" },
  { latex: "\\iint", label: "∬", description: "double integral" },
  { latex: "\\iiint", label: "∭", description: "triple integral" },
  { latex: "\\oint", label: "∮", description: "contour integral" },
  { latex: "\\oiint", label: "∯", description: "surface integral" },
  { latex: "\\oiiint", label: "∰", description: "volume integral" },
  { latex: "\\partial", label: "∂", description: "partial derivative" },
  { latex: "\\nabla", label: "∇", description: "nabla / del / gradient" },
  { latex: "\\infty", label: "∞", description: "infinity" },
  { latex: "\\sum", label: "∑", description: "summation" },
  { latex: "\\prod", label: "∏", description: "product" },
  { latex: "\\coprod", label: "∐", description: "coproduct" },
  { latex: "\\lim", label: "lim", description: "limit" },
  { latex: "\\lim_{x \\to 0}", label: "lim→0", description: "limit as x→0" },
  { latex: "\\lim_{x \\to \\infty}", label: "lim→∞", description: "limit as x→∞" },
  { latex: "\\limsup", label: "lim sup", description: "limit superior" },
  { latex: "\\liminf", label: "lim inf", description: "limit inferior" },
  { latex: "\\sup", label: "sup", description: "supremum" },
  { latex: "\\inf", label: "inf", description: "infimum" },
  { latex: "\\max", label: "max", description: "maximum" },
  { latex: "\\min", label: "min", description: "minimum" },
  { latex: "\\frac{d}{dx}", label: "d/dx", description: "derivative d/dx" },
  { latex: "\\frac{dy}{dx}", label: "dy/dx", description: "derivative dy/dx" },
  { latex: "\\frac{d^2y}{dx^2}", label: "d²y/dx²", description: "second derivative" },
  { latex: "\\frac{\\partial f}{\\partial x}", label: "∂f/∂x", description: "partial derivative f/x" },
  { latex: "\\frac{d^n}{dx^n}", label: "dⁿ/dxⁿ", description: "nth derivative" },
  { latex: "\\int_{a}^{b}", label: "∫ₐᵇ", description: "definite integral a to b" },
  { latex: "\\sum_{i=1}^{n}", label: "∑ᵢ₌₁ⁿ", description: "sum from 1 to n" },
  { latex: "\\prod_{i=1}^{n}", label: "∏ᵢ₌₁ⁿ", description: "product from 1 to n" },
  { latex: "f'(x)", label: "f′(x)", description: "prime notation derivative" },
  { latex: "f''(x)", label: "f″(x)", description: "double prime derivative" },
  { latex: "\\dot{x}", label: "ẋ", description: "dot notation (time derivative)" },
  { latex: "\\ddot{x}", label: "ẍ", description: "double dot (second time deriv)" },
  { latex: "\\Delta x", label: "Δx", description: "change in x" },
  { latex: "\\delta x", label: "δx", description: "small change in x" },
  { latex: "dx", label: "dx", description: "differential dx" },
  { latex: "\\mathrm{e}", label: "e", description: "Euler's number" },
  { latex: "e^x", label: "eˣ", description: "exponential" },
  { latex: "\\ln x", label: "ln x", description: "natural log" },
  { latex: "\\log x", label: "log x", description: "common log" },
  { latex: "\\log_{a} x", label: "logₐx", description: "log base a" },
  { latex: "\\exp(x)", label: "exp(x)", description: "exponential function" },
  { latex: "\\sinh", label: "sinh", description: "hyperbolic sine" },
  { latex: "\\cosh", label: "cosh", description: "hyperbolic cosine" },
  { latex: "\\tanh", label: "tanh", description: "hyperbolic tangent" },
  { latex: "\\arcsinh", label: "arcsinh", description: "inverse hyperbolic sine" },
  { latex: "\\text{sgn}", label: "sgn", description: "sign function" },
  { latex: "\\|x\\|", label: "‖x‖", description: "norm" },
  { latex: "|x|", label: "|x|", description: "absolute value" },
  { latex: "\\lfloor x \\rfloor", label: "⌊x⌋", description: "floor function" },
  { latex: "\\lceil x \\rceil", label: "⌈x⌉", description: "ceiling function" },
];

// ── Trigonometry ──────────────────────────────────────────────────────────────
const TRIGONOMETRY: LatexSymbol[] = [
  { latex: "\\sin", label: "sin", description: "sine" },
  { latex: "\\cos", label: "cos", description: "cosine" },
  { latex: "\\tan", label: "tan", description: "tangent" },
  { latex: "\\cot", label: "cot", description: "cotangent" },
  { latex: "\\sec", label: "sec", description: "secant" },
  { latex: "\\csc", label: "csc", description: "cosecant" },
  { latex: "\\arcsin", label: "arcsin", description: "arcsine (sin⁻¹)" },
  { latex: "\\arccos", label: "arccos", description: "arccosine (cos⁻¹)" },
  { latex: "\\arctan", label: "arctan", description: "arctangent (tan⁻¹)" },
  { latex: "\\sin^{-1}", label: "sin⁻¹", description: "inverse sine" },
  { latex: "\\cos^{-1}", label: "cos⁻¹", description: "inverse cosine" },
  { latex: "\\tan^{-1}", label: "tan⁻¹", description: "inverse tangent" },
  { latex: "\\sin^{2}", label: "sin²", description: "sine squared" },
  { latex: "\\cos^{2}", label: "cos²", description: "cosine squared" },
  { latex: "\\sin(\\theta)", label: "sin(θ)", description: "sin theta" },
  { latex: "\\cos(\\theta)", label: "cos(θ)", description: "cos theta" },
  { latex: "\\tan(\\theta)", label: "tan(θ)", description: "tan theta" },
  { latex: "\\sin^2 \\theta + \\cos^2 \\theta = 1", label: "sin²θ+cos²θ=1", description: "Pythagorean identity" },
  { latex: "\\frac{\\pi}{2}", label: "π/2", description: "pi over 2 (90°)" },
  { latex: "\\frac{\\pi}{3}", label: "π/3", description: "pi over 3 (60°)" },
  { latex: "\\frac{\\pi}{4}", label: "π/4", description: "pi over 4 (45°)" },
  { latex: "\\frac{\\pi}{6}", label: "π/6", description: "pi over 6 (30°)" },
  { latex: "180^{\\circ}", label: "180°", description: "180 degrees" },
  { latex: "90^{\\circ}", label: "90°", description: "90 degrees" },
  { latex: "^{\\circ}", label: "°", description: "degree symbol" },
  { latex: "\\angle", label: "∠", description: "angle" },
  { latex: "\\measuredangle", label: "∡", description: "measured angle" },
  { latex: "\\sphericalangle", label: "∢", description: "spherical angle" },
];

// ── Geometry ──────────────────────────────────────────────────────────────────
const GEOMETRY: LatexSymbol[] = [
  { latex: "\\angle", label: "∠", description: "angle" },
  { latex: "\\triangle", label: "△", description: "triangle" },
  { latex: "\\square", label: "□", description: "square" },
  { latex: "\\diamond", label: "◇", description: "diamond" },
  { latex: "\\circ", label: "∘", description: "circle / composition" },
  { latex: "\\perp", label: "⊥", description: "perpendicular" },
  { latex: "\\parallel", label: "∥", description: "parallel" },
  { latex: "\\nparallel", label: "∦", description: "not parallel" },
  { latex: "\\cong", label: "≅", description: "congruent" },
  { latex: "\\ncong", label: "≇", description: "not congruent" },
  { latex: "\\sim", label: "∼", description: "similar" },
  { latex: "\\nsim", label: "≁", description: "not similar" },
  { latex: "\\overline{AB}", label: "AB̄", description: "line segment AB" },
  { latex: "\\overrightarrow{AB}", label: "AB→", description: "ray AB" },
  { latex: "\\overleftrightarrow{AB}", label: "AB↔", description: "line AB" },
  { latex: "\\pi r^2", label: "πr²", description: "area of circle" },
  { latex: "2\\pi r", label: "2πr", description: "circumference" },
  { latex: "\\frac{4}{3}\\pi r^3", label: "4/3πr³", description: "volume of sphere" },
  { latex: "\\frac{1}{2}bh", label: "½bh", description: "area of triangle" },
  { latex: "a^2 + b^2 = c^2", label: "a²+b²=c²", description: "Pythagorean theorem" },
  { latex: "\\vec{v}", label: "v⃗", description: "vector v" },
  { latex: "\\hat{n}", label: "n̂", description: "unit vector n" },
  { latex: "\\widehat{ABC}", label: "ÂBC", description: "hat over ABC" },
  { latex: "\\overarc{AB}", label: "A⌢B", description: "arc AB" },
  { latex: "\\measuredangle", label: "∡", description: "measured angle" },
];

// ── Fractions, Powers & Templates ─────────────────────────────────────────────
const FRACTIONS_POWERS: LatexSymbol[] = [
  { latex: "\\frac{a}{b}", label: "a/b", description: "fraction a over b" },
  { latex: "\\frac{1}{2}", label: "½", description: "one half" },
  { latex: "\\frac{1}{3}", label: "⅓", description: "one third" },
  { latex: "\\frac{1}{4}", label: "¼", description: "one quarter" },
  { latex: "\\frac{3}{4}", label: "¾", description: "three quarters" },
  { latex: "\\frac{2}{3}", label: "⅔", description: "two thirds" },
  { latex: "x^{2}", label: "x²", description: "x squared" },
  { latex: "x^{3}", label: "x³", description: "x cubed" },
  { latex: "x^{n}", label: "xⁿ", description: "x to the n" },
  { latex: "x^{-1}", label: "x⁻¹", description: "x inverse" },
  { latex: "x^{-n}", label: "x⁻ⁿ", description: "x to the minus n" },
  { latex: "x_{1}", label: "x₁", description: "x sub 1" },
  { latex: "x_{n}", label: "xₙ", description: "x sub n" },
  { latex: "x_{i}", label: "xᵢ", description: "x sub i" },
  { latex: "\\sqrt{x}", label: "√x", description: "square root" },
  { latex: "\\sqrt[3]{x}", label: "³√x", description: "cube root" },
  { latex: "\\sqrt[n]{x}", label: "ⁿ√x", description: "nth root" },
  { latex: "x^{\\frac{1}{2}}", label: "x^½", description: "x to the one-half" },
  { latex: "x^{\\frac{m}{n}}", label: "x^m/n", description: "rational exponent" },
  { latex: "10^{x}", label: "10ˣ", description: "power of 10" },
  { latex: "2^{n}", label: "2ⁿ", description: "power of 2" },
  { latex: "a^{m} \\cdot a^{n}", label: "aᵐ·aⁿ", description: "product of powers" },
  { latex: "\\dfrac{a}{b}", label: "a⁄b", description: "display fraction (larger)" },
  { latex: "\\cfrac{a}{b}", label: "a/b", description: "continued fraction" },
  { latex: "\\binom{n}{k}", label: "nCk", description: "binomial coefficient" },
  { latex: "\\binom{n}{r}", label: "nCr", description: "combinations n choose r" },
  { latex: "n!", label: "n!", description: "factorial" },
  { latex: "\\frac{n!}{(n-r)!}", label: "nPr", description: "permutations nPr" },
  { latex: "\\frac{n!}{r!(n-r)!}", label: "nCr", description: "combinations formula" },
  { latex: "{}_n P_r", label: "ₙPᵣ", description: "permutation notation" },
  { latex: "{}_n C_r", label: "ₙCᵣ", description: "combination notation" },
];

// ── Accents & Decorations ─────────────────────────────────────────────────────
const ACCENTS: LatexSymbol[] = [
  { latex: "\\hat{x}", label: "x̂", description: "hat accent" },
  { latex: "\\bar{x}", label: "x̄", description: "bar (mean)" },
  { latex: "\\vec{x}", label: "x⃗", description: "vector arrow" },
  { latex: "\\tilde{x}", label: "x̃", description: "tilde" },
  { latex: "\\dot{x}", label: "ẋ", description: "dot (derivative)" },
  { latex: "\\ddot{x}", label: "ẍ", description: "double dot" },
  { latex: "\\acute{x}", label: "x́", description: "acute accent" },
  { latex: "\\grave{x}", label: "x̀", description: "grave accent" },
  { latex: "\\check{x}", label: "x̌", description: "check accent" },
  { latex: "\\breve{x}", label: "x̆", description: "breve accent" },
  { latex: "\\mathring{x}", label: "x̊", description: "ring accent" },
  { latex: "\\overline{x}", label: "x̄", description: "overline" },
  { latex: "\\underline{x}", label: "x̲", description: "underline" },
  { latex: "\\overbrace{x}", label: "⏞x", description: "overbrace" },
  { latex: "\\underbrace{x}", label: "x⏟", description: "underbrace" },
  { latex: "\\widehat{xyz}", label: "x̂yz", description: "wide hat" },
  { latex: "\\widetilde{xyz}", label: "x̃yz", description: "wide tilde" },
  { latex: "\\overrightarrow{xyz}", label: "xyz→", description: "over right arrow" },
  { latex: "\\overleftarrow{xyz}", label: "←xyz", description: "over left arrow" },
  { latex: "\\boxed{x}", label: "⊡x", description: "boxed expression" },
];

// ── Brackets & Delimiters ─────────────────────────────────────────────────────
const BRACKETS: LatexSymbol[] = [
  { latex: "(x)", label: "(x)", description: "parentheses" },
  { latex: "[x]", label: "[x]", description: "square brackets" },
  { latex: "\\{x\\}", label: "{x}", description: "curly braces" },
  { latex: "\\langle x \\rangle", label: "⟨x⟩", description: "angle brackets" },
  { latex: "|x|", label: "|x|", description: "absolute value bars" },
  { latex: "\\|x\\|", label: "‖x‖", description: "norm double bars" },
  { latex: "\\lfloor x \\rfloor", label: "⌊x⌋", description: "floor brackets" },
  { latex: "\\lceil x \\rceil", label: "⌈x⌉", description: "ceiling brackets" },
  { latex: "\\left( x \\right)", label: "( x )", description: "auto-sized parentheses" },
  { latex: "\\left[ x \\right]", label: "[ x ]", description: "auto-sized square brackets" },
  { latex: "\\left\\{ x \\right\\}", label: "{ x }", description: "auto-sized curly braces" },
  { latex: "\\left| x \\right|", label: "| x |", description: "auto-sized abs value" },
  { latex: "\\left\\| x \\right\\|", label: "‖ x ‖", description: "auto-sized norm" },
  { latex: "\\left\\lfloor x \\right\\rfloor", label: "⌊ x ⌋", description: "auto-sized floor" },
  { latex: "\\left\\lceil x \\rceil", label: "⌈ x ⌉", description: "auto-sized ceiling" },
  { latex: "\\left\\langle x \\right\\rangle", label: "⟨ x ⟩", description: "auto-sized angle" },
  { latex: "(a, b)", label: "(a,b)", description: "open interval" },
  { latex: "[a, b]", label: "[a,b]", description: "closed interval" },
  { latex: "(a, b]", label: "(a,b]", description: "half-open interval" },
  { latex: "[a, b)", label: "[a,b)", description: "half-open interval (left)" },
];

// ── Physics ───────────────────────────────────────────────────────────────────
const PHYSICS: LatexSymbol[] = [
  // Mechanics
  { latex: "F = ma", label: "F=ma", description: "Newton's second law" },
  { latex: "W = Fd", label: "W=Fd", description: "Work done" },
  { latex: "P = \\frac{W}{t}", label: "P=W/t", description: "Power" },
  { latex: "E_k = \\frac{1}{2}mv^2", label: "KE=½mv²", description: "Kinetic energy" },
  { latex: "E_p = mgh", label: "PE=mgh", description: "Potential energy" },
  { latex: "v = u + at", label: "v=u+at", description: "SUVAT v" },
  { latex: "s = ut + \\frac{1}{2}at^2", label: "s=ut+½at²", description: "SUVAT s" },
  { latex: "v^2 = u^2 + 2as", label: "v²=u²+2as", description: "SUVAT v²" },
  { latex: "p = mv", label: "p=mv", description: "Momentum" },
  { latex: "\\rho = \\frac{m}{V}", label: "ρ=m/V", description: "Density" },
  { latex: "\\text{P} = \\frac{F}{A}", label: "P=F/A", description: "Pressure" },
  { latex: "\\tau = r \\times F", label: "τ=r×F", description: "Torque" },
  { latex: "\\omega = \\frac{v}{r}", label: "ω=v/r", description: "Angular velocity" },
  { latex: "T = 2\\pi\\sqrt{\\frac{l}{g}}", label: "T=2π√(l/g)", description: "Period of pendulum" },
  { latex: "F_g = \\frac{Gm_1 m_2}{r^2}", label: "Fg=Gm₁m₂/r²", description: "Gravitational force" },
  // Waves & Optics
  { latex: "v = f\\lambda", label: "v=fλ", description: "Wave speed" },
  { latex: "f = \\frac{1}{T}", label: "f=1/T", description: "Frequency" },
  { latex: "n = \\frac{c}{v}", label: "n=c/v", description: "Refractive index" },
  { latex: "\\frac{\\sin i}{\\sin r} = n", label: "sini/sinr=n", description: "Snell's law" },
  { latex: "\\frac{1}{f} = \\frac{1}{u} + \\frac{1}{v}", label: "1/f=1/u+1/v", description: "Lens formula" },
  // Electricity
  { latex: "V = IR", label: "V=IR", description: "Ohm's law" },
  { latex: "P = IV", label: "P=IV", description: "Electrical power" },
  { latex: "P = I^2 R", label: "P=I²R", description: "Power in resistor" },
  { latex: "P = \\frac{V^2}{R}", label: "P=V²/R", description: "Power (V,R)" },
  { latex: "Q = It", label: "Q=It", description: "Charge" },
  { latex: "E = \\frac{Q}{4\\pi\\epsilon_0 r^2}", label: "E=Q/4πε₀r²", description: "Electric field" },
  { latex: "F = \\frac{Q_1 Q_2}{4\\pi\\epsilon_0 r^2}", label: "Coulomb's law", description: "Coulomb's law" },
  // Thermodynamics
  { latex: "Q = mc\\Delta T", label: "Q=mcΔT", description: "Heat energy" },
  { latex: "PV = nRT", label: "PV=nRT", description: "Ideal gas law" },
  { latex: "\\eta = 1 - \\frac{T_c}{T_h}", label: "η=1-Tc/Th", description: "Carnot efficiency" },
  // Atomic
  { latex: "E = hf", label: "E=hf", description: "Photon energy (Planck)" },
  { latex: "E = mc^2", label: "E=mc²", description: "Mass-energy equivalence" },
  { latex: "\\lambda = \\frac{h}{mv}", label: "λ=h/mv", description: "de Broglie wavelength" },
  // Constants
  { latex: "g = 9.8\\,\\text{m/s}^2", label: "g=9.8m/s²", description: "gravitational acceleration" },
  { latex: "c = 3\\times 10^8\\,\\text{m/s}", label: "c=3×10⁸m/s", description: "speed of light" },
  { latex: "h = 6.63\\times 10^{-34}\\,\\text{J·s}", label: "h=6.63×10⁻³⁴Js", description: "Planck constant" },
  { latex: "N_A = 6.02\\times 10^{23}", label: "Nₐ=6.02×10²³", description: "Avogadro's number" },
  // Symbols
  { latex: "\\hbar", label: "ℏ", description: "h-bar (reduced Planck)" },
  { latex: "\\epsilon_0", label: "ε₀", description: "permittivity of free space" },
  { latex: "\\mu_0", label: "μ₀", description: "permeability of free space" },
];

// ── Chemistry ─────────────────────────────────────────────────────────────────
const CHEMISTRY: LatexSymbol[] = [
  // States and symbols
  { latex: "\\rightleftharpoons", label: "⇌", description: "equilibrium arrows" },
  { latex: "\\rightarrow", label: "→", description: "reaction arrow" },
  { latex: "_{(aq)}", label: "(aq)", description: "aqueous" },
  { latex: "_{(s)}", label: "(s)", description: "solid" },
  { latex: "_{(l)}", label: "(l)", description: "liquid" },
  { latex: "_{(g)}", label: "(g)", description: "gas" },
  { latex: "\\Delta", label: "Δ", description: "heat / change" },
  { latex: "\\Delta H", label: "ΔH", description: "enthalpy change" },
  { latex: "\\Delta G", label: "ΔG", description: "Gibbs free energy" },
  { latex: "\\Delta S", label: "ΔS", description: "entropy change" },
  { latex: "K_a", label: "Ka", description: "acid dissociation constant" },
  { latex: "K_b", label: "Kb", description: "base dissociation constant" },
  { latex: "K_c", label: "Kc", description: "equilibrium constant (conc)" },
  { latex: "K_{sp}", label: "Ksp", description: "solubility product" },
  { latex: "K_w", label: "Kw", description: "water dissociation constant" },
  { latex: "K_p", label: "Kp", description: "equilibrium constant (pressure)" },
  { latex: "\\text{pH} = -\\log[H^+]", label: "pH=-log[H⁺]", description: "pH definition" },
  { latex: "[H^+][OH^-] = 10^{-14}", label: "[H⁺][OH⁻]=10⁻¹⁴", description: "Kw" },
  // Molecular formulas
  { latex: "H_2O", label: "H₂O", description: "water" },
  { latex: "CO_2", label: "CO₂", description: "carbon dioxide" },
  { latex: "O_2", label: "O₂", description: "oxygen gas" },
  { latex: "H_2", label: "H₂", description: "hydrogen gas" },
  { latex: "N_2", label: "N₂", description: "nitrogen gas" },
  { latex: "H_2SO_4", label: "H₂SO₄", description: "sulfuric acid" },
  { latex: "HCl", label: "HCl", description: "hydrochloric acid" },
  { latex: "NaOH", label: "NaOH", description: "sodium hydroxide" },
  { latex: "CaCO_3", label: "CaCO₃", description: "calcium carbonate" },
  { latex: "NH_3", label: "NH₃", description: "ammonia" },
  { latex: "CH_4", label: "CH₄", description: "methane" },
  { latex: "C_6H_{12}O_6", label: "C₆H₁₂O₆", description: "glucose" },
  { latex: "C_{12}H_{22}O_{11}", label: "C₁₂H₂₂O₁₁", description: "sucrose" },
  { latex: "Na_2CO_3", label: "Na₂CO₃", description: "sodium carbonate" },
  { latex: "CuSO_4", label: "CuSO₄", description: "copper sulfate" },
  { latex: "H_3O^+", label: "H₃O⁺", description: "hydronium ion" },
  { latex: "OH^-", label: "OH⁻", description: "hydroxide ion" },
  { latex: "Cl^-", label: "Cl⁻", description: "chloride ion" },
  { latex: "Na^+", label: "Na⁺", description: "sodium ion" },
  { latex: "Ca^{2+}", label: "Ca²⁺", description: "calcium ion" },
  { latex: "Fe^{3+}", label: "Fe³⁺", description: "iron(III) ion" },
  // Calculations
  { latex: "n = \\frac{m}{M}", label: "n=m/M", description: "moles = mass/molar mass" },
  { latex: "n = \\frac{N}{N_A}", label: "n=N/Nₐ", description: "moles = particles/Avogadro" },
  { latex: "c = \\frac{n}{V}", label: "c=n/V", description: "concentration" },
  { latex: "PV = nRT", label: "PV=nRT", description: "ideal gas law" },
  { latex: "\\text{\\%yield} = \\frac{\\text{actual}}{\\text{theoretical}} \\times 100", label: "%yield", description: "percentage yield" },
  { latex: "\\text{M}_r", label: "Mr", description: "relative molecular mass" },
  { latex: "\\text{A}_r", label: "Ar", description: "relative atomic mass" },
];

// ── Statistics & Probability ──────────────────────────────────────────────────
const STATISTICS: LatexSymbol[] = [
  { latex: "\\bar{x}", label: "x̄", description: "sample mean" },
  { latex: "\\mu", label: "μ", description: "population mean" },
  { latex: "\\sigma", label: "σ", description: "standard deviation (pop)" },
  { latex: "s", label: "s", description: "sample standard deviation" },
  { latex: "\\sigma^2", label: "σ²", description: "variance (population)" },
  { latex: "s^2", label: "s²", description: "variance (sample)" },
  { latex: "\\bar{x} = \\frac{\\sum x}{n}", label: "x̄=Σx/n", description: "mean formula" },
  { latex: "\\sigma = \\sqrt{\\frac{\\sum(x-\\mu)^2}{N}}", label: "σ=√(Σ(x-μ)²/N)", description: "std deviation formula" },
  { latex: "P(A)", label: "P(A)", description: "probability of A" },
  { latex: "P(A \\cup B)", label: "P(A∪B)", description: "P(A or B)" },
  { latex: "P(A \\cap B)", label: "P(A∩B)", description: "P(A and B)" },
  { latex: "P(A|B)", label: "P(A|B)", description: "conditional probability" },
  { latex: "P(A') = 1 - P(A)", label: "P(A')=1-P(A)", description: "complement probability" },
  { latex: "P(A \\cup B) = P(A) + P(B) - P(A \\cap B)", label: "addition rule", description: "addition rule of probability" },
  { latex: "P(A \\cap B) = P(A) \\cdot P(B|A)", label: "multiplication rule", description: "multiplication rule" },
  { latex: "^n C_r = \\binom{n}{r}", label: "nCr", description: "combinations" },
  { latex: "^n P_r = \\frac{n!}{(n-r)!}", label: "nPr", description: "permutations" },
  { latex: "\\text{Median}", label: "Med", description: "median" },
  { latex: "\\text{Mode}", label: "Mode", description: "mode" },
  { latex: "\\text{Range} = x_{max} - x_{min}", label: "Range", description: "range" },
  { latex: "Q_1, Q_2, Q_3", label: "Q1,Q2,Q3", description: "quartiles" },
  { latex: "\\text{IQR} = Q_3 - Q_1", label: "IQR=Q3-Q1", description: "interquartile range" },
  { latex: "z = \\frac{x - \\mu}{\\sigma}", label: "z-score", description: "z-score" },
  { latex: "r_{xy}", label: "rxy", description: "correlation coefficient" },
  { latex: "\\rho", label: "ρ", description: "Pearson correlation (pop)" },
  { latex: "X \\sim N(\\mu, \\sigma^2)", label: "X~N(μ,σ²)", description: "normal distribution" },
  { latex: "X \\sim B(n, p)", label: "X~B(n,p)", description: "binomial distribution" },
  { latex: "E(X)", label: "E(X)", description: "expected value" },
  { latex: "\\text{Var}(X)", label: "Var(X)", description: "variance of X" },
];

// ── Matrices & Vectors ────────────────────────────────────────────────────────
const MATRICES: LatexSymbol[] = [
  { latex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}", label: "2×2 matrix", description: "2x2 parenthesis matrix" },
  { latex: "\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}", label: "[2×2]", description: "2x2 bracket matrix" },
  { latex: "\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}", label: "|2×2|", description: "determinant 2x2" },
  { latex: "\\det(A)", label: "det(A)", description: "determinant" },
  { latex: "A^{-1}", label: "A⁻¹", description: "matrix inverse" },
  { latex: "A^T", label: "Aᵀ", description: "matrix transpose" },
  { latex: "\\text{tr}(A)", label: "tr(A)", description: "matrix trace" },
  { latex: "A^H", label: "Aᴴ", description: "conjugate transpose (Hermitian)" },
  { latex: "\\text{rank}(A)", label: "rank(A)", description: "matrix rank" },
  { latex: "\\|A\\|", label: "‖A‖", description: "matrix norm" },
  { latex: "\\lambda", label: "λ", description: "eigenvalue" },
  { latex: "Av = \\lambda v", label: "Av=λv", description: "eigenvalue equation" },
  { latex: "\\vec{a} \\cdot \\vec{b}", label: "a·b", description: "dot product" },
  { latex: "\\vec{a} \\times \\vec{b}", label: "a×b", description: "cross product" },
  { latex: "|\\vec{v}|", label: "|v|", description: "vector magnitude" },
  { latex: "\\hat{i}, \\hat{j}, \\hat{k}", label: "i,j,k", description: "unit vectors" },
  { latex: "\\begin{pmatrix} x \\\\ y \\end{pmatrix}", label: "col vector", description: "column vector" },
  { latex: "\\begin{pmatrix} x & y \\end{pmatrix}", label: "row vector", description: "row vector" },
  { latex: "I_n", label: "Iₙ", description: "identity matrix n×n" },
  { latex: "0_{m \\times n}", label: "0ₘₓₙ", description: "zero matrix" },
];

// ── Number Theory ─────────────────────────────────────────────────────────────
const NUMBER_THEORY: LatexSymbol[] = [
  { latex: "\\gcd(a,b)", label: "gcd", description: "greatest common divisor" },
  { latex: "\\text{lcm}(a,b)", label: "lcm", description: "least common multiple" },
  { latex: "a \\mid b", label: "a|b", description: "a divides b" },
  { latex: "a \\nmid b", label: "a∤b", description: "a does not divide b" },
  { latex: "a \\equiv b \\pmod{n}", label: "a≡b(mod n)", description: "congruence mod n" },
  { latex: "a \\bmod n", label: "a mod n", description: "a modulo n" },
  { latex: "\\lfloor x \\rfloor", label: "⌊x⌋", description: "floor function" },
  { latex: "\\lceil x \\rceil", label: "⌈x⌉", description: "ceiling function" },
  { latex: "\\{x\\}", label: "{x}", description: "fractional part" },
  { latex: "\\phi(n)", label: "φ(n)", description: "Euler's totient function" },
  { latex: "\\phi", label: "φ", description: "golden ratio / Euler totient" },
  { latex: "\\pi(x)", label: "π(x)", description: "prime counting function" },
  { latex: "\\sum_{d|n}", label: "Σd|n", description: "sum over divisors of n" },
  { latex: "\\mathbb{Z}/n\\mathbb{Z}", label: "ℤ/nℤ", description: "integers mod n" },
  { latex: "p \\equiv 1 \\pmod{4}", label: "p≡1(mod 4)", description: "p congruent 1 mod 4" },
  { latex: "2^{n} - 1", label: "2ⁿ-1", description: "Mersenne number" },
  { latex: "\\left(\\frac{a}{p}\\right)", label: "Legendre", description: "Legendre symbol" },
];

// ── Algebra & Polynomials ─────────────────────────────────────────────────────
const ALGEBRA: LatexSymbol[] = [
  { latex: "ax^2 + bx + c = 0", label: "quadratic", description: "quadratic equation" },
  { latex: "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}", label: "quad formula", description: "quadratic formula" },
  { latex: "b^2 - 4ac", label: "discriminant", description: "discriminant" },
  { latex: "(a+b)^2 = a^2 + 2ab + b^2", label: "(a+b)²", description: "perfect square" },
  { latex: "(a-b)^2 = a^2 - 2ab + b^2", label: "(a-b)²", description: "perfect square (minus)" },
  { latex: "(a+b)(a-b) = a^2 - b^2", label: "diff of squares", description: "difference of squares" },
  { latex: "(a+b)^3 = a^3 + 3a^2b + 3ab^2 + b^3", label: "(a+b)³", description: "cube expansion" },
  { latex: "a^3 - b^3 = (a-b)(a^2+ab+b^2)", label: "diff of cubes", description: "difference of cubes" },
  { latex: "a^3 + b^3 = (a+b)(a^2-ab+b^2)", label: "sum of cubes", description: "sum of cubes" },
  { latex: "\\sum_{k=0}^{n} \\binom{n}{k} a^{n-k} b^k", label: "binomial thm", description: "binomial theorem" },
  { latex: "(1+x)^n \\approx 1 + nx", label: "binomial approx", description: "binomial approximation" },
  { latex: "f(x) = a_n x^n + \\ldots + a_1 x + a_0", label: "polynomial", description: "general polynomial" },
  { latex: "\\alpha + \\beta = -\\frac{b}{a}", label: "sum of roots", description: "sum of roots" },
  { latex: "\\alpha \\beta = \\frac{c}{a}", label: "product of roots", description: "product of roots" },
  { latex: "|x| < a \\Rightarrow -a < x < a", label: "|x|<a", description: "absolute value inequality" },
  { latex: "\\log_a(xy) = \\log_a x + \\log_a y", label: "log product", description: "log product rule" },
  { latex: "\\log_a\\left(\\frac{x}{y}\\right) = \\log_a x - \\log_a y", label: "log quotient", description: "log quotient rule" },
  { latex: "\\log_a(x^n) = n\\log_a x", label: "log power", description: "log power rule" },
  { latex: "\\log_a x = \\frac{\\log x}{\\log a}", label: "change of base", description: "change of base formula" },
  { latex: "a^x = e^{x\\ln a}", label: "aˣ=e^xlna", description: "exponential change of base" },
  { latex: "A_n = A_0 r^n", label: "geometric seq", description: "geometric sequence" },
  { latex: "A_n = A_0 + nd", label: "arithmetic seq", description: "arithmetic sequence" },
  { latex: "S_n = \\frac{n}{2}(a+l)", label: "arith sum", description: "sum of arithmetic series" },
  { latex: "S_n = \\frac{a(r^n - 1)}{r-1}", label: "geom sum", description: "sum of geometric series" },
  { latex: "S_\\infty = \\frac{a}{1-r}", label: "S∞=a/(1-r)", description: "infinite geometric series" },
];

// ── SI Units ──────────────────────────────────────────────────────────────────
const SI_UNITS: LatexSymbol[] = [
  { latex: "\\text{m}", label: "m", description: "metre" },
  { latex: "\\text{kg}", label: "kg", description: "kilogram" },
  { latex: "\\text{s}", label: "s", description: "second" },
  { latex: "\\text{A}", label: "A", description: "ampere" },
  { latex: "\\text{K}", label: "K", description: "kelvin" },
  { latex: "\\text{mol}", label: "mol", description: "mole" },
  { latex: "\\text{cd}", label: "cd", description: "candela" },
  { latex: "\\text{N}", label: "N", description: "newton" },
  { latex: "\\text{J}", label: "J", description: "joule" },
  { latex: "\\text{W}", label: "W", description: "watt" },
  { latex: "\\text{Pa}", label: "Pa", description: "pascal" },
  { latex: "\\text{V}", label: "V", description: "volt" },
  { latex: "\\text{C}", label: "C", description: "coulomb" },
  { latex: "\\text{\\Omega}", label: "Ω", description: "ohm" },
  { latex: "\\text{F}", label: "F", description: "farad" },
  { latex: "\\text{H}", label: "H", description: "henry" },
  { latex: "\\text{T}", label: "T", description: "tesla" },
  { latex: "\\text{Hz}", label: "Hz", description: "hertz" },
  { latex: "\\text{lm}", label: "lm", description: "lumen" },
  { latex: "\\text{lx}", label: "lx", description: "lux" },
  { latex: "\\text{Bq}", label: "Bq", description: "becquerel" },
  { latex: "\\text{Gy}", label: "Gy", description: "gray" },
  { latex: "\\text{Sv}", label: "Sv", description: "sievert" },
  // Prefixes
  { latex: "\\text{G}", label: "G (giga)", description: "giga 10⁹" },
  { latex: "\\text{M}", label: "M (mega)", description: "mega 10⁶" },
  { latex: "\\text{k}", label: "k (kilo)", description: "kilo 10³" },
  { latex: "\\text{c}", label: "c (centi)", description: "centi 10⁻²" },
  { latex: "\\text{m}", label: "m (milli)", description: "milli 10⁻³" },
  { latex: "\\mu", label: "μ (micro)", description: "micro 10⁻⁶" },
  { latex: "\\text{n}", label: "n (nano)", description: "nano 10⁻⁹" },
  { latex: "\\text{p}", label: "p (pico)", description: "pico 10⁻¹²" },
  { latex: "\\text{T}", label: "T (tera)", description: "tera 10¹²" },
  // Common combos
  { latex: "\\text{km}", label: "km", description: "kilometre" },
  { latex: "\\text{cm}", label: "cm", description: "centimetre" },
  { latex: "\\text{mm}", label: "mm", description: "millimetre" },
  { latex: "\\text{km/h}", label: "km/h", description: "kilometres per hour" },
  { latex: "\\text{m/s}", label: "m/s", description: "metres per second" },
  { latex: "\\text{m/s}^2", label: "m/s²", description: "metres per second squared" },
  { latex: "\\text{kPa}", label: "kPa", description: "kilopascal" },
  { latex: "\\text{kJ}", label: "kJ", description: "kilojoule" },
  { latex: "\\text{kW}", label: "kW", description: "kilowatt" },
  { latex: "\\text{kWh}", label: "kWh", description: "kilowatt-hour" },
  { latex: "\\text{°C}", label: "°C", description: "degrees Celsius" },
  { latex: "\\text{mA}", label: "mA", description: "milliampere" },
  { latex: "\\text{μF}", label: "μF", description: "microfarad" },
  { latex: "\\text{mH}", label: "mH", description: "millihenry" },
  { latex: "\\text{kΩ}", label: "kΩ", description: "kilohm" },
  { latex: "\\text{MΩ}", label: "MΩ", description: "megaohm" },
];

// ── Miscellaneous ─────────────────────────────────────────────────────────────
const MISC: LatexSymbol[] = [
  { latex: "\\ldots", label: "…", description: "ellipsis (baseline)" },
  { latex: "\\cdots", label: "⋯", description: "ellipsis (centered)" },
  { latex: "\\vdots", label: "⋮", description: "vertical dots" },
  { latex: "\\ddots", label: "⋱", description: "diagonal dots" },
  { latex: "\\prime", label: "′", description: "prime" },
  { latex: "\\dprime", label: "″", description: "double prime" },
  { latex: "\\infty", label: "∞", description: "infinity" },
  { latex: "\\aleph", label: "ℵ", description: "aleph (transfinite cardinals)" },
  { latex: "\\beth", label: "ℶ", description: "beth" },
  { latex: "\\gimel", label: "ℷ", description: "gimel" },
  { latex: "\\daleth", label: "ℸ", description: "daleth" },
  { latex: "\\Re", label: "ℜ", description: "real part" },
  { latex: "\\Im", label: "ℑ", description: "imaginary part" },
  { latex: "\\wp", label: "℘", description: "Weierstrass p" },
  { latex: "\\ell", label: "ℓ", description: "script l" },
  { latex: "\\hbar", label: "ℏ", description: "h-bar" },
  { latex: "\\imath", label: "ı", description: "dotless i" },
  { latex: "\\jmath", label: "ȷ", description: "dotless j" },
  { latex: "\\sharp", label: "♯", description: "music sharp" },
  { latex: "\\flat", label: "♭", description: "music flat" },
  { latex: "\\natural", label: "♮", description: "music natural" },
  { latex: "\\surd", label: "√", description: "radical sign" },
  { latex: "\\copyright", label: "©", description: "copyright" },
  { latex: "\\registered", label: "®", description: "registered" },
  { latex: "\\trademark", label: "™", description: "trademark" },
  { latex: "\\pounds", label: "£", description: "pound sterling" },
  { latex: "\\euro", label: "€", description: "euro" },
  { latex: "\\yen", label: "¥", description: "yen" },
  { latex: "\\S", label: "§", description: "section symbol" },
  { latex: "\\P", label: "¶", description: "paragraph symbol" },
  { latex: "\\%", label: "%", description: "percent" },
  { latex: "\\permil", label: "‰", description: "per mille" },
  { latex: "\\#", label: "#", description: "hash" },
  { latex: "\\&", label: "&", description: "ampersand" },
  { latex: "\\square", label: "□", description: "square (QED box)" },
  { latex: "\\blacksquare", label: "■", description: "filled square (QED)" },
  { latex: "\\checkmark", label: "✓", description: "checkmark" },
  { latex: "\\dagger", label: "†", description: "dagger" },
  { latex: "\\ddagger", label: "‡", description: "double dagger" },
  { latex: "\\spadesuit", label: "♠", description: "spade" },
  { latex: "\\heartsuit", label: "♡", description: "heart" },
  { latex: "\\diamondsuit", label: "♢", description: "diamond" },
  { latex: "\\clubsuit", label: "♣", description: "club" },
];

// ── Big Operators ─────────────────────────────────────────────────────────────
const BIG_OPERATORS: LatexSymbol[] = [
  { latex: "\\sum_{i=1}^{n} i = \\frac{n(n+1)}{2}", label: "∑i=n(n+1)/2", description: "sum of first n integers" },
  { latex: "\\sum_{i=1}^{n} i^2 = \\frac{n(n+1)(2n+1)}{6}", label: "∑i²", description: "sum of squares" },
  { latex: "\\sum_{i=1}^{n} i^3 = \\left(\\frac{n(n+1)}{2}\\right)^2", label: "∑i³", description: "sum of cubes" },
  { latex: "\\sum_{n=0}^{\\infty} ar^n = \\frac{a}{1-r}", label: "∑arⁿ=a/(1-r)", description: "geometric series sum" },
  { latex: "\\sum_{n=0}^{\\infty} \\frac{x^n}{n!} = e^x", label: "Maclaurin eˣ", description: "exponential series" },
  { latex: "\\prod_{i=1}^{n} i = n!", label: "∏i=n!", description: "product = factorial" },
  { latex: "\\int_0^\\infty e^{-x} dx = 1", label: "∫₀^∞e⁻ˣ=1", description: "Laplace/Gamma(1)" },
  { latex: "\\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}", label: "Gaussian integral", description: "Gaussian integral" },
  { latex: "\\frac{d}{dx}[x^n] = nx^{n-1}", label: "power rule", description: "power rule" },
  { latex: "\\frac{d}{dx}[e^x] = e^x", label: "d/dx eˣ=eˣ", description: "derivative of eˣ" },
  { latex: "\\frac{d}{dx}[\\ln x] = \\frac{1}{x}", label: "d/dx ln=1/x", description: "derivative of ln" },
  { latex: "\\frac{d}{dx}[\\sin x] = \\cos x", label: "d/dx sin=cos", description: "derivative of sin" },
  { latex: "\\frac{d}{dx}[\\cos x] = -\\sin x", label: "d/dx cos=-sin", description: "derivative of cos" },
  { latex: "\\frac{d}{dx}[\\tan x] = \\sec^2 x", label: "d/dx tan=sec²", description: "derivative of tan" },
  { latex: "\\int x^n dx = \\frac{x^{n+1}}{n+1} + C", label: "∫xⁿ", description: "power rule integral" },
  { latex: "\\int e^x dx = e^x + C", label: "∫eˣ=eˣ", description: "integral of eˣ" },
  { latex: "\\int \\frac{1}{x} dx = \\ln|x| + C", label: "∫1/x=ln|x|", description: "integral of 1/x" },
  { latex: "\\int \\sin x\\, dx = -\\cos x + C", label: "∫sin=-cos", description: "integral of sin" },
  { latex: "\\int \\cos x\\, dx = \\sin x + C", label: "∫cos=sin", description: "integral of cos" },
];

// ── Number Formats ────────────────────────────────────────────────────────────
const NUMBER_FORMATS: LatexSymbol[] = [
  { latex: "\\times 10^{}", label: "×10ⁿ", description: "scientific notation" },
  { latex: "1.0 \\times 10^{3}", label: "1×10³", description: "1000 in sci notation" },
  { latex: "6.02 \\times 10^{23}", label: "6.02×10²³", description: "Avogadro" },
  { latex: "3 \\times 10^{8}", label: "3×10⁸", description: "speed of light" },
  { latex: "\\overline{0.\\dot{3}}", label: "0.3̄", description: "recurring decimal" },
  { latex: "\\frac{22}{7}", label: "22/7", description: "22/7 (approx π)" },
  { latex: "\\sqrt{2} \\approx 1.414", label: "√2≈1.414", description: "root 2" },
  { latex: "\\sqrt{3} \\approx 1.732", label: "√3≈1.732", description: "root 3" },
  { latex: "\\pi \\approx 3.14159", label: "π≈3.14159", description: "pi value" },
  { latex: "e \\approx 2.71828", label: "e≈2.71828", description: "Euler's number" },
  { latex: "\\phi = \\frac{1+\\sqrt{5}}{2}", label: "φ=(1+√5)/2", description: "golden ratio" },
  { latex: "i = \\sqrt{-1}", label: "i=√(-1)", description: "imaginary unit" },
  { latex: "z = a + bi", label: "z=a+bi", description: "complex number" },
  { latex: "|z| = \\sqrt{a^2 + b^2}", label: "|z|=√(a²+b²)", description: "complex modulus" },
  { latex: "\\arg(z) = \\arctan\\frac{b}{a}", label: "arg(z)", description: "argument of z" },
  { latex: "e^{i\\pi} + 1 = 0", label: "Euler's identity", description: "Euler's identity" },
  { latex: "e^{i\\theta} = \\cos\\theta + i\\sin\\theta", label: "Euler's formula", description: "Euler's formula" },
  { latex: "\\overline{z} = a - bi", label: "z̄=a-bi", description: "complex conjugate" },
];

// ── Full Category List ────────────────────────────────────────────────────────
export const SYMBOL_CATEGORIES: SymbolCategory[] = [
  { id: "greek-lower", name: "Greek (lower)", symbols: GREEK_LOWER },
  { id: "greek-upper", name: "Greek (upper)", symbols: GREEK_UPPER },
  { id: "algebra", name: "Algebra", symbols: ALGEBRA },
  { id: "fractions-powers", name: "Fractions & Powers", symbols: FRACTIONS_POWERS },
  { id: "calculus", name: "Calculus", symbols: CALCULUS },
  { id: "big-operators", name: "Formulas", symbols: BIG_OPERATORS },
  { id: "trigonometry", name: "Trigonometry", symbols: TRIGONOMETRY },
  { id: "geometry", name: "Geometry", symbols: GEOMETRY },
  { id: "statistics", name: "Statistics", symbols: STATISTICS },
  { id: "matrices", name: "Matrices & Vectors", symbols: MATRICES },
  { id: "sets-logic", name: "Sets & Logic", symbols: SETS_LOGIC },
  { id: "number-theory", name: "Number Theory", symbols: NUMBER_THEORY },
  { id: "number-formats", name: "Complex & Numbers", symbols: NUMBER_FORMATS },
  { id: "operators", name: "Operators", symbols: OPERATORS },
  { id: "relations", name: "Relations", symbols: RELATIONS },
  { id: "arrows", name: "Arrows", symbols: ARROWS },
  { id: "accents", name: "Accents", symbols: ACCENTS },
  { id: "brackets", name: "Brackets", symbols: BRACKETS },
  { id: "physics", name: "Physics", symbols: PHYSICS },
  { id: "chemistry", name: "Chemistry", symbols: CHEMISTRY },
  { id: "si-units", name: "SI Units", symbols: SI_UNITS },
  { id: "misc", name: "Miscellaneous", symbols: MISC },
];

// Flat list for search
export const ALL_SYMBOLS: LatexSymbol[] = SYMBOL_CATEGORIES.flatMap((c) =>
  c.symbols.map((s) => s),
);

export function searchSymbols(query: string): LatexSymbol[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return ALL_SYMBOLS.filter(
    (s) =>
      s.description.toLowerCase().includes(q) ||
      s.latex.toLowerCase().includes(q) ||
      s.label.toLowerCase().includes(q),
  ).slice(0, 80);
}
