import Link from "next/link";
import { BarChart2, ChevronRight, FileText, Globe, History, PenLine, Upload, Users, ClipboardList } from "lucide-react";
import { requireSchool } from "@/lib/auth";
import { db } from "@/lib/db";
import { PageHeader } from "@/components/ui/PageHeader";
import { SectionHeader } from "@/components/ui/SectionHeader";
import { DataList, ActivityRow } from "@/components/ui/DataList";
import { MetricStrip } from "@/components/ui/MetricStrip";
import { StatusBadge } from "@/components/ui/Status";

export const metadata = { title: "Student Data Hub — TeachNexis" };

export default async function StudentHubPage() {
  const { schoolId } = await requireSchool();
  const [classCount, studentCount, importJobCount, syncLogCount, recentJobs] = await Promise.all([
    db.class.count({ where: { schoolId } }), db.student.count({ where: { schoolId, isActive: true } }), db.importJob.count({ where: { schoolId, status: "COMMITTED" } }), db.syncLog.count({ where: { schoolId } }), db.importJob.findMany({ where: { schoolId }, orderBy: { createdAt: "desc" }, take: 5, select: { id: true, source: true, status: true, totalRows: true, createdAt: true, fileName: true } }),
  ]);
  const methods = [{ href: "/classes", icon: Users, title: "1. Classes", desc: "Create or choose the class your records belong to." }, { href: "/student-hub/import", icon: Upload, title: "2. Import students", desc: "Upload a CSV or spreadsheet student register." }, { href: "/student-hub/manual", icon: PenLine, title: "3. Manual entry", desc: "Add classes, students, and results by hand." }, { href: "/student-hub/portal", icon: Globe, title: "Portal sync", desc: "Connect an available school portal integration." }];
  const tools = [{ href: "/attendance", icon: ClipboardList, label: "Attendance", desc: "Mark and review attendance" }, { href: "/scores", icon: ClipboardList, label: "Scores", desc: "Enter and review results" }, { href: "/student-hub/reports", icon: FileText, label: "Reports", desc: "Generate factual school reports" }, { href: "/student-hub/sync-history", icon: History, label: "Sync history", desc: "Review imports and sync operations" }, { href: "/student-hub/analytics", icon: BarChart2, label: "Analytics", desc: "Explore recorded score data" }];
  return <div className="mx-auto max-w-6xl space-y-7"><PageHeader title="Student Data Hub" description="A clear path from class setup to records, imports, and reports." /><MetricStrip items={[{ label: "Classes", value: classCount, detail: "School roster" }, { label: "Active students", value: studentCount, detail: "School roster" }, { label: "Completed imports", value: importJobCount }, { label: "Sync operations", value: syncLogCount }]} /><section aria-labelledby="setup-heading"><SectionHeader title={<span id="setup-heading">Set up and maintain records</span>} description="Start with the class, then choose how to add or maintain students." /><div className="mt-3 rounded-xl border border-border bg-surface p-2"><DataList label="Student record workflows">{methods.map(({ href, icon: Icon, title, desc }) => <ActivityRow key={href} leading={<span className="flex size-9 items-center justify-center rounded-lg bg-primary-50"><Icon size={18} className="text-primary" /></span>} title={<Link href={href} className="hover:text-primary">{title}</Link>} description={desc} action={<ChevronRight size={16} className="text-muted" aria-hidden="true" />} />)}</DataList></div></section><section aria-labelledby="tools-heading"><SectionHeader title={<span id="tools-heading">Students & records</span>} description="Open the record workflow you need." /><div className="mt-3 rounded-xl border border-border bg-surface p-2"><DataList label="Student record tools">{tools.map(({ href, icon: Icon, label, desc }) => <ActivityRow key={href} leading={<Icon size={18} className="text-primary" aria-hidden="true" />} title={<Link href={href} className="hover:text-primary">{label}</Link>} description={desc} action={<ChevronRight size={16} className="text-muted" aria-hidden="true" />} />)}</DataList></div></section>{recentJobs.length > 0 && <section aria-labelledby="history-heading"><SectionHeader title={<span id="history-heading">Recent imports</span>} action={<Link href="/student-hub/sync-history" className="text-sm font-medium text-primary hover:underline">View history</Link>} /><div className="mt-3 rounded-xl border border-border bg-surface p-2"><DataList label="Recent imports">{recentJobs.map((job) => <ActivityRow key={job.id} leading={<History size={18} className="text-text-2" aria-hidden="true" />} title={job.fileName ?? `${job.source} import`} description={`${job.totalRows} rows · ${new Date(job.createdAt).toLocaleDateString("en-NG")}`} meta={<StatusBadge tone={job.status === "COMMITTED" ? "success" : job.status === "FAILED" ? "error" : "pending"}>{job.status}</StatusBadge>} />)}</DataList></div></section>}</div>;
}
