"use client";
import { useState } from "react";
import Link from "next/link";
import { Logo } from "@/components/brand/Logo";
import { Menu, X } from "lucide-react";

const NAV_LINKS = [{ href: "#workspace", label: "How it works" }, { href: "#features", label: "For teachers" }, { href: "#assessment", label: "Assessment" }, { href: "#faq", label: "Resources" }];

export function LandingNav() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return <nav aria-label="Public navigation" className="absolute left-0 right-0 top-0 z-50 border-b border-slate-200/70 bg-[#fdf8f0]/90 backdrop-blur-sm"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6 sm:px-10 lg:px-16"><Link href="/" aria-label="TeachNexis home"><Logo variant="dark" size="md" /></Link><div className="hidden items-center gap-1 md:flex">{NAV_LINKS.map((link) => <a key={link.href} href={link.href} className="rounded-md px-3 py-2 text-sm font-medium text-slate-600 transition hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600">{link.label}</a>)}</div><div className="flex items-center gap-2"><Link href="/sign-in" className="hidden rounded-md px-3 py-2 text-sm font-medium text-slate-600 hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 md:inline-flex">Sign in</Link><Link href="/sign-up" className="inline-flex min-h-10 items-center rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600">Get started</Link><button type="button" onClick={() => setMobileOpen((open) => !open)} aria-expanded={mobileOpen} aria-controls="landing-mobile-menu" aria-label={mobileOpen ? "Close menu" : "Open menu"} className="inline-flex min-h-10 min-w-10 items-center justify-center rounded-md text-slate-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 md:hidden">{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button></div></div>{mobileOpen && <div id="landing-mobile-menu" className="border-t border-slate-200 bg-[#fdf8f0] px-6 py-4 md:hidden"><div className="flex flex-col gap-1">{NAV_LINKS.map((link) => <a key={link.href} href={link.href} onClick={() => setMobileOpen(false)} className="rounded-md px-3 py-3 text-sm font-medium text-slate-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600">{link.label}</a>)}<Link href="/sign-in" onClick={() => setMobileOpen(false)} className="rounded-md px-3 py-3 text-sm font-medium text-slate-700">Sign in</Link></div></div>}</nav>;
}
