"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createManualLesson, createPastedLesson, createManualLessonFromSource } from "@/app/actions/lessons";
import type { LessonSourceReference } from "@/lib/lessons/content-envelope";
import type { ClassLevel } from "@prisma/client";

const levels: ClassLevel[] = ["JS1", "JS2", "JS3", "SS1", "SS2", "SS3"];
type SourceSelection = { document: { title: string; subject: string; classLevel: string | null }; chunk: { id: string; content: string }; sourceReference: LessonSourceReference };
export function ManualLessonClient({ mode, sourceSelection }: { mode: "manual" | "paste"; sourceSelection?: SourceSelection | null }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const [form, setForm] = useState({ subject: sourceSelection?.document.subject ?? "", classLevel: (sourceSelection?.document.classLevel ?? "") as ClassLevel | "", topic: sourceSelection?.document.title ?? "", term: "FIRST", week: "", periods: "1", markdown: sourceSelection?.chunk.content ?? "" });
  const submit = () => { if (!form.subject || !form.classLevel || !form.topic || !form.markdown.trim()) return; startTransition(async () => { const common = { ...form, classLevel: form.classLevel as ClassLevel, week: form.week ? Number(form.week) : undefined, periods: Number(form.periods), markdown: form.markdown }; const id = mode === "paste" ? await createPastedLesson({ ...common, sourceRepresentation: form.markdown }) : sourceSelection ? await createManualLessonFromSource({ ...common, sourceDocumentId: sourceSelection.sourceReference.documentId, sourceChunkId: sourceSelection.chunk.id }) : await createManualLesson(common); router.push(`/lessons/${id}`); }); };
  return <div className="space-y-5 rounded-xl border border-border bg-surface p-5">
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-text-2">Subject<select value={form.subject} onChange={e => setForm({...form, subject:e.target.value})} className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm"><option value="">Select subject</option>{["Mathematics","English Language","Physics","Chemistry","Biology","Further Mathematics"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm text-text-2">Class level<select value={form.classLevel} onChange={e => setForm({...form, classLevel:e.target.value as ClassLevel})} className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm"><option value="">Select class</option>{levels.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm text-text-2">Term<select value={form.term} onChange={e => setForm({...form, term:e.target.value})} className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm"><option>FIRST</option><option>SECOND</option><option>THIRD</option></select></label><label className="text-sm text-text-2">Week (optional)<input value={form.week} onChange={e=>setForm({...form,week:e.target.value})} type="number" min="1" className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm" /></label><label className="text-sm text-text-2 sm:col-span-2">Topic<input value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})} className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm" /></label></div>
    <label className="block text-sm text-text-2">{mode === "paste" ? "Original note" : "Lesson content"}<textarea value={form.markdown} onChange={e=>setForm({...form,markdown:e.target.value})} rows={16} className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 font-mono text-sm leading-relaxed" placeholder={mode === "paste" ? "Paste your note exactly as written…" : "Write your lesson in Markdown…"} /></label>
    {mode === "paste" && <p className="text-xs text-text-2">Your pasted source is preserved exactly. You can edit a draft later without losing the original.</p>}
    {sourceSelection && <div className="rounded-lg border border-primary/20 bg-primary-50/40 p-3"><p className="text-xs font-semibold text-primary">Source evidence attached</p><p className="text-sm text-text mt-1">{sourceSelection.document.title}</p><p className="text-xs text-text-2 mt-1 whitespace-pre-wrap break-words">{sourceSelection.chunk.content}</p><p className="text-xs text-muted mt-1">The evidence remains attached even if you edit the working lesson.</p></div>}
    <button onClick={submit} disabled={pending || !form.subject || !form.classLevel || !form.topic || !form.markdown.trim()} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{pending ? "Saving draft…" : "Save draft"}</button>
  </div>;
}
