"use client";

import { useState, useTransition } from "react";
import { saveTeacherGrade, releaseTeacherResult } from "@/app/actions/grading";
import { StatusMessage } from "@/components/ui/Status";
import { MathText } from "@/components/ui/MathText";

type Item = { id: string; questionId: string; order: number; marks: number; type: string; stem: string; correctOption: string | null; solution: string | null; response: { id: string; selectedOption: string | null; textResponse: string | null; score: number | null; feedback: string | null; gradedAt: Date | null } | null };
type Data = { attempt: { id: string; status: string; submittedAt: Date | null; totalScore: number | null; maxScore: number | null; percentage: number | null; resultReleasedAt: Date | null }; publication: { version: number; title: string; resultReleasePolicy: string; answerReleasePolicy: string }; student: { name: string; regNumber: string | null }; items: Item[] };

export function TeacherGradingClient({ data }: { data: Data }) {
  const [marks, setMarks] = useState<Record<string, string>>(() => Object.fromEntries(data.items.map((item) => [item.id, item.response?.score?.toString() ?? ""] )));
  const [feedback, setFeedback] = useState<Record<string, string>>(() => Object.fromEntries(data.items.map((item) => [item.id, item.response?.feedback ?? ""] )));
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const save = (item: Item) => startTransition(async () => { setError(null); setMessage(null); const value = Number(marks[item.id]); if (!Number.isFinite(value)) { setError("Enter a valid mark."); return; } try { await saveTeacherGrade({ attemptId: data.attempt.id, publicationItemId: item.id, awardedMarks: value, feedback: feedback[item.id] || null }); setMessage("Grade saved."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save grade."); } });
  const release = () => startTransition(async () => { setError(null); setMessage(null); try { await releaseTeacherResult(data.attempt.id); setMessage("Result released to the student."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to release result."); } });
  return <div className="mx-auto max-w-4xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-wide text-primary">Grading</p><h1 className="mt-1 text-2xl font-bold text-text">{data.publication.title}</h1><p className="mt-1 text-sm text-text-2">{data.student.name}{data.student.regNumber ? ` · ${data.student.regNumber}` : ""} · Publication {data.publication.version}</p></header>{(message || error) && <StatusMessage tone={error ? "error" : "success"}>{error ?? message}</StatusMessage>}<div className="rounded-xl border border-border bg-surface p-4"><p className="text-sm text-text-2">Progress: {data.attempt.totalScore ?? 0} / {data.attempt.maxScore ?? 0} marks · {data.attempt.percentage?.toFixed(1) ?? "0.0"}%</p></div><div className="space-y-4">{data.items.map((item) => <article key={item.id} className="rounded-xl border border-border bg-surface p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold leading-6 text-text">{item.order}. <MathText text={item.stem} /></h2><span className="shrink-0 text-xs font-semibold text-text-2">Max {item.marks}</span></div><p className="mt-3 text-sm text-text-2">Student answer: <span className="font-medium text-text">{item.response?.selectedOption ?? <MathText text={item.response?.textResponse ?? "Unanswered"} />}</span></p><div className="mt-4 grid gap-3 sm:grid-cols-[10rem_1fr]"><label className="text-sm font-medium text-text">Awarded marks<input type="number" min="0" max={item.marks} step="0.5" value={marks[item.id]} onChange={(e) => setMarks((all) => ({ ...all, [item.id]: e.target.value }))} aria-describedby={`max-${item.id}`} className="mt-1 w-full rounded-lg border border-border bg-canvas px-3 py-2" /><span id={`max-${item.id}`} className="text-xs text-text-2">0 to {item.marks}</span></label><label className="text-sm font-medium text-text">Feedback<textarea value={feedback[item.id]} onChange={(e) => setFeedback((all) => ({ ...all, [item.id]: e.target.value }))} rows={2} className="mt-1 w-full rounded-lg border border-border bg-canvas px-3 py-2" /></label></div><button type="button" onClick={() => save(item)} disabled={pending || Boolean(data.attempt.resultReleasedAt)} className="mt-3 min-h-10 rounded-lg bg-primary px-4 text-sm font-semibold text-white disabled:opacity-50">{pending ? "Saving…" : "Save grade"}</button></article>)}</div>{!data.attempt.resultReleasedAt && <button type="button" onClick={release} disabled={pending || data.attempt.status !== "GRADED"} className="min-h-11 rounded-lg bg-primary px-5 text-sm font-semibold text-white disabled:opacity-50">Release result</button>}</div>;
}
