"use client";

import { useState, useTransition } from "react";
import { getAssessmentScoreTransferPreview, transferAssessmentScoreComponent } from "@/app/actions/assessment-analytics";
import { StatusMessage } from "@/components/ui/Status";

type Component = { id: string; name: string; maxScore: number | null };
export function AssessmentScoreBridge({ examId, components }: { examId: string; components: Component[] }) {
  const [componentId, setComponentId] = useState(components[0]?.id ?? ""); const [preview, setPreview] = useState<{ assessmentTotal: number; component: { name: string; maxScore: number | null }; rows: Array<{ name: string; rawScore: number; normalizedScore: number; conflict: string }> } | null>(null); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const loadPreview = () => startTransition(async () => { setError(null); try { setPreview(await getAssessmentScoreTransferPreview(examId, componentId)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to prepare transfer preview."); } });
  const transfer = (conflict: "SKIP" | "REPLACE") => startTransition(async () => { setError(null); try { const result = await transferAssessmentScoreComponent({ examId, componentId, conflict }); setMessage(`${result.transferred} transferred. ${result.skipped} skipped.`); } catch (e) { setError(e instanceof Error ? e.message : "Transfer failed."); } });
  return <aside className="space-y-3 rounded-xl border border-border bg-surface p-4"><h2 className="font-semibold text-text">Send to official results</h2><p className="text-xs leading-5 text-text-2">This is an explicit component transfer. Score.total and supplied TAVG remain unchanged.</p>{components.length === 0 ? <p className="text-sm text-text-2">No active assessment components are configured.</p> : <><label className="block text-sm font-medium text-text">Target component<select value={componentId} onChange={(e) => setComponentId(e.target.value)} className="mt-1 w-full rounded-lg border border-border bg-canvas px-3 py-2">{components.map((component) => <option key={component.id} value={component.id}>{component.name}{component.maxScore ? ` (${component.maxScore})` : ""}</option>)}</select></label><button type="button" onClick={loadPreview} disabled={pending || !componentId} className="min-h-10 rounded-lg border border-border px-3 text-sm font-semibold">{pending ? "Preparing…" : "Preview transfer"}</button></>}{(message || error) && <StatusMessage tone={error ? "error" : "success"}>{error ?? message}</StatusMessage>}{preview && <div className="space-y-2 text-xs text-text-2"><p>Assessment total: <strong>{preview.assessmentTotal}</strong> · Component max: <strong>{preview.component.maxScore ?? "same"}</strong></p><p>{preview.rows.length} graded students · normalized values shown below</p><ul className="max-h-40 space-y-1 overflow-y-auto">{preview.rows.map((row) => <li key={row.name} className="flex justify-between gap-2"><span>{row.name}</span><span>{row.rawScore} → {row.normalizedScore} · {row.conflict.replaceAll("_", " ")}</span></li>)}</ul><div className="flex flex-wrap gap-2"><button type="button" onClick={() => transfer("SKIP")} disabled={pending} className="min-h-10 rounded-lg bg-primary px-3 text-xs font-semibold text-white">Transfer; skip conflicts</button><button type="button" onClick={() => transfer("REPLACE")} disabled={pending} className="min-h-10 rounded-lg border border-danger/30 px-3 text-xs font-semibold text-danger">Replace conflicts</button></div></div>}</aside>;
}
