import type { LessonNoteContract, LessonStages } from "./v2-contract";
import { createTeacherReflectionTemplate, LESSON_V2_CONTRACT_VERSION } from "./v2-contract";
import { validateLessonContract, validateStages, type ValidationResult } from "./v2-validation";

export function assembleLesson(stages: Partial<Record<1 | 2 | 3 | 4 | 5, LessonStages[number]>>): { contract: LessonNoteContract | null; validation: ValidationResult } {
  const stageCheck = validateStages(stages);
  if (stageCheck.status === "BLOCKED") return { contract: null, validation: stageCheck };
  const s1 = stages[1] as import("./v2-contract").Stage1ContextPlanning, s2 = stages[2] as import("./v2-contract").Stage2InstructionalExplanation, s3 = stages[3] as import("./v2-contract").Stage3PedagogyWorkedPractice, s4 = stages[4] as import("./v2-contract").Stage4ApplicationsExamination, s5 = stages[5] as import("./v2-contract").Stage5Closure;
  const contract: LessonNoteContract = { contractVersion: LESSON_V2_CONTRACT_VERSION, metadata: s1.metadata, curriculum: s1.curriculum, instruction: { materials: s2.materials, vocabulary: s1.vocabulary, hook: s2.hook, symbolsNotation: s1.symbolsNotation, history: s2.history, teachingContent: s2.teachingContent, activities: s3.activities, differentiation: s3.differentiation, misconceptions: s3.misconceptions, formativeAssessment: s3.formativeAssessment, higherOrderQuestions: s3.higherOrderQuestions, applications: s4.applications }, workedExamples: s3.workedExamples, assessment: { examinationGuidance: s4.examinationGuidance, examinationItems: s4.examinationItems, classExercise: s5.classExercise, boardSummary: s5.boardSummary, comingNext: s5.comingNext, homework: s5.homework, studentSummary: s5.studentSummary, teacherReflection: createTeacherReflectionTemplate() }, stem: s2.stem, provenance: { ...s1.provenance, stages: { ...s1.provenance.stages, "1": { status: "COMPLETED" }, "2": { status: "COMPLETED" }, "3": { status: "COMPLETED" }, "4": { status: "COMPLETED" }, "5": { status: "COMPLETED" } } }, validation: { status: "PASS", errors: [], warnings: [] } };
  const validation = validateLessonContract(contract, s1.metadata); contract.validation = { status: validation.status, errors: validation.errors.map((x) => x.message), warnings: validation.warnings.map((x) => x.message) }; return { contract, validation };
}

export function renderLessonMarkdown(c: LessonNoteContract): string {
  const m = c.metadata, lines = [`## Lesson Note: ${m.topic}`, "", "---", "", "### SECTION 1 — LESSON METADATA", `- Subject: ${m.subject}`, `- Class: ${m.classLevel}`, `- Topic: ${m.topic}`, `- Duration: ${m.durationMinutes} minutes`, `- Term: ${m.term ?? "—"}`, `- Week: ${m.week ?? "—"}`, "", "### SECTION 2 — CURRICULUM ALIGNMENT & LEARNING OBJECTIVES", ...c.curriculum.objectives.map((x) => `- ${x}`), "", "### SECTION 3 — ENTRY BEHAVIOUR", ...c.curriculum.entryBehaviour.map((x) => `- ${x.topic}${x.classLevel ? ` — ${x.classLevel}` : ""}`), "", "### SECTION 4 — LESSON HOOK", c.instruction.hook, "", "### SECTION 5 — TOPIC ROADMAP", ...c.curriculum.roadmap.map((x, i) => `${i + 1}. ${x.title} — ${x.status}`), "", "### SECTION 6 — TEACHING MATERIALS & RESOURCES", ...c.instruction.materials.map((x) => `- ${x}`), "", "### SECTION 7 — KEY VOCABULARY", ...c.instruction.vocabulary.map((x) => `- **${x.term}:** ${x.definition} (${x.analogy})`), "", "### SECTION 8 — SYMBOLS AND NOTATION", c.instruction.symbolsNotation, "", "### SECTION 9 — HISTORICAL / DISCOVERY CONTEXT", c.instruction.history, "", "### SECTION 10 — TEACHING CONTENT", c.instruction.teachingContent, "", "### SECTION 11 — WORKED EXAMPLES — 5 LEVELS", ...c.workedExamples.map((x) => `**Example ${x.level}**\n\n**Q:** ${x.question}\n\n**Solution:** ${x.solution}${x.markScheme ? `\n\n**Mark scheme:** ${x.markScheme}` : ""}`), "", "### SECTION 12 — COMMON MISCONCEPTIONS & CORRECTIONS", c.instruction.misconceptions, "", "### SECTION 13 — CLASSROOM ACTIVITIES", c.instruction.activities, "", "### SECTION 14 — DIFFERENTIATED INSTRUCTION", c.instruction.differentiation, "", "### SECTION 15 — FORMATIVE ASSESSMENT", c.instruction.formativeAssessment, "", "### SECTION 16 — HIGHER ORDER THINKING QUESTIONS", c.instruction.higherOrderQuestions, "", "### SECTION 17 — REAL-WORLD APPLICATIONS & CROSS-CURRICULAR CONNECTIONS", c.instruction.applications, "", "### SECTION 18 — WAEC / NECO / JAMB INTELLIGENCE", c.assessment.examinationGuidance, ...c.assessment.examinationItems.map((x) => `- [${x.sourceStatus}] ${x.question}\n  Answer: ${x.answer}`), "", "### SECTION 19 — CLASS EXERCISE", ...c.assessment.classExercise.map((x, i) => `${i + 1}. ${x}`), "", "### SECTION 20 — BOARD SUMMARY", ...c.assessment.boardSummary.map((x) => `- ${x}`), "", "### SECTION 21 — COMING UP NEXT", c.assessment.comingNext, "", "### SECTION 22 — HOMEWORK ASSIGNMENT (4 Levels)", c.assessment.homework, "", "### SECTION 23 — LESSON SUMMARY (Student Revision Notes)", c.assessment.studentSummary, "", "### SECTION 24 — TEACHER REFLECTION TEMPLATE", ...c.assessment.teacherReflection.prompts.map((x) => `- ${x}`)];
  return lines.join("\n");
}
