import type { LessonMetadata, LessonSourceContext } from "./v2-contract";
import { roadmapLimitForPeriods } from "./v2-validation";

export interface StagePromptInput { metadata: LessonMetadata; curriculumContext?: string[]; textbookContext?: string[]; source?: LessonSourceContext; contentOrigin?: import("./v2-contract").LessonContentOrigin; stemSource?: string; stemWarnings?: string[]; }
const base = (stage: string, input: StagePromptInput, fields: string) => `You are a TeachNexis lesson author. Produce JSON only for ${stage}. Request metadata: ${JSON.stringify(input.metadata)}. Curriculum context (use only if supplied): ${JSON.stringify(input.curriculumContext ?? [])}. Textbook/source excerpts (do not invent provenance): ${JSON.stringify(input.textbookContext ?? input.source?.excerpts ?? [])}. Return only these fields: ${fields}. Use Nigerian classroom relevance and preserve mathematical/scientific notation exactly. No placeholders, TODOs, TBDs, or unsupported examination claims. Teacher remains the final authority; do not publish content.`;
export const buildStage1Prompt = (i: StagePromptInput) => base("Stage 1 — Context & Planning", i, "curriculum, vocabulary, symbolsNotation");
export const buildStage1APrompt = (i: StagePromptInput) => `${base("Stage 1A — Lesson Identity & Curriculum", i, "curriculumCore, vocabulary, symbolsNotation only; do not include entry behaviour, diagnostics, roadmap, teaching content, examples, or assessment")} Return exactly this shape: {"curriculumCore":{"objectives":["string"],"learningOutcomes":["string"],"bloomsDistribution":{"REMEMBER":["string"]}},"vocabulary":[{"term":"string","definition":"string","analogy":"string"}],"symbolsNotation":"string"}. Vocabulary must be an array of objects with exactly term, definition, and analogy string fields (never strings or alternate key names). symbolsNotation must be one string containing the lesson notation; do not return an array or object.`;
export const buildStage1BPrompt = (i: StagePromptInput) => `${base("Stage 1B — Entry & Diagnostic", i, "entryBehaviour, diagnosticQuestions only; do not include objectives, roadmap, teaching content, examples, or assessment")} Return exactly this shape: {"entryBehaviour":[{"topic":"string","classLevel":"string","term":"string"}],"diagnosticQuestions":["string"]}. diagnosticQuestions must be a non-empty array of unique question strings; do not return objects or a single string.`;
export const buildStage1CPrompt = (i: StagePromptInput) => { const max = roadmapLimitForPeriods(i.metadata.periods); return `${base("Stage 1C — Roadmap", i, "roadmap only: an ordered array of concise {title,status} entries; statuses COVERED, NEXT, or FUTURE; do not include IDs or teaching explanations")} Return between 1 and ${max} roadmap items. Never exceed ${max}. Items are major lesson steps only: do not make examples, activities, vocabulary, or assessment separate roadmap items. Detailed teaching belongs to later stages.`; };
export const buildStage2Prompt = (i: StagePromptInput) => base("Stage 2 — Instructional Explanation", i, "materials, hook, history, teachingContent, stem");
export const buildStage2APrompt = (i: StagePromptInput) => base("Stage 2A — Materials, Context & Core Explanation", i, "materials, hook, history, teachingContent only; do not include stem or notation fields");
export const buildStage2BPrompt = (i: StagePromptInput) => base("Stage 2B — STEM & Notation", i, "stem only, preserving canonical sourceRepresentation and any renderedRepresentation/conversionWarnings; do not include teaching prose");
export const buildStage2A1Prompt = (i: StagePromptInput) => `${base("Stage 2A1 — Instructional Context", i, "materials (string[]), hook (string), history (string|null) only; do not include teachingContent, workedExamples, assessment, or homework")} Include all three exact keys. Use history:null when no meaningful, reliable historical context exists; never invent history or use N/A.`;
export const buildTeachingContentChunkPrompt = (i: StagePromptInput, _roadmapId: string, roadmapIndex: number, title: string) => `${base(`Teaching Content Chunk ${roadmapIndex + 1}`, i, "content only")} You are generating teaching content ONLY for the supplied roadmap item: ${title}. Return exactly {"content":"string"}. Keep content between 180 and 650 words: explain sufficiently for classroom teaching, then finish the JSON object; do not continue merely to add verbosity. Do not return roadmapId, roadmapIndex, title, or any other bookkeeping fields. Do not create, rename, reorder, insert, or remove roadmap items. Do not include worked examples, activities, assessment, homework, or unrelated lesson sections. No placeholders.`;
export const buildStage3Prompt = (i: StagePromptInput) => base("Stage 3 — Pedagogy & Worked Practice", i, "workedExamples (exactly five, levels 1-5), misconceptions, activities, differentiation, formativeAssessment, higherOrderQuestions");
export const buildStage3APrompt = (i: StagePromptInput) => base("Stage 3A — Worked Examples", i, "workedExamples only (exactly five objects, levels 1-5, progressively harder, each with question and complete solution, optional markScheme)");
export const buildStage3BPrompt = (i: StagePromptInput) => base("Stage 3B — Pedagogy & Practice", i, "misconceptions, activities, differentiation, formativeAssessment, higherOrderQuestions only");
export const buildStage3B1Prompt = (i: StagePromptInput) => base("Stage 3B1 — Classroom Pedagogy", i, "misconceptions, activities, differentiation only; do not include formativeAssessment, higherOrderQuestions, workedExamples, or homework");
export const buildStage3B1APrompt = (i: StagePromptInput) => base("Stage 3B1A — Misconceptions", i, "misconceptions only as a string; do not include activities, differentiation, formativeAssessment, higherOrderQuestions, workedExamples, homework, examinations, or other sections");
export const buildStage3B1BPrompt = (i: StagePromptInput) => base("Stage 3B1B — Classroom Activities", i, "activities only as a string; do not include misconceptions, differentiation, formativeAssessment, higherOrderQuestions, workedExamples, homework, examinations, or other sections");
export const buildStage3B1CPrompt = (i: StagePromptInput) => base("Stage 3B1C — Differentiation", i, "differentiation only as a string; do not include misconceptions, activities, formativeAssessment, higherOrderQuestions, workedExamples, homework, examinations, or other sections");
export const buildStage3B2Prompt = (i: StagePromptInput) => `${base("Stage 3B2 — Formative Assessment & Thinking", i, "formativeAssessment, higherOrderQuestions only; do not include workedExamples, homework, or examination claims")} Return exactly this JSON shape: {"formativeAssessment":"string","higherOrderQuestions":"string"}. Both values must be non-empty strings. Do not use alternate key names, nested wrappers, arrays, or prose outside JSON. Do not include placeholders, examinations, or sections owned by other stages.`;
export const buildStage4APrompt = (i: StagePromptInput) => `${base("Stage 4A — Applications & Examination Guidance", i, "applications, examinationGuidance only; do not include examinationItems, workedExamples, homework, classExercise, or other lesson sections")} Return exactly this JSON shape: {"applications":"string","examinationGuidance":"string"}. Both values must be concise, non-empty strings. Do not include placeholders or examination questions.`;
export const buildStage4BPrompt = (i: StagePromptInput) => `${base("Stage 4B — Examination Items", i, "examinationItems only; do not include applications, examinationGuidance, workedExamples, homework, classExercise, or other lesson sections")} Return exactly this JSON shape: {"examinationItems":[{"sourceStatus":"GENERATED_EXAM_STYLE","examStyle":"WAEC|NECO|JAMB|null","question":"string","answer":"string"}]}. Every item must be GENERATED_EXAM_STYLE unless actual retrieved evidence is supplied. Use VERIFIED_RETRIEVED_SOURCE only with sourceId, excerpt and retrievedAt from supplied evidence; never invent years, paper numbers, question numbers or citations. Generated items must not contain evidence. Return a JSON object only, with no prose or placeholders.`;
export const buildStage4Prompt = (i: StagePromptInput) => `${base("Stage 4 — Applications & Examination Preparation", i, "applications, examinationGuidance, examinationItems")} Every item must be GENERATED_EXAM_STYLE unless actual retrieved evidence is supplied. Use VERIFIED_RETRIEVED_SOURCE only with sourceId, excerpt and retrievedAt from supplied evidence; never invent years, paper numbers, question numbers or citations. examStyle is WAEC, NECO, JAMB, or null.`;
export const buildStage5APrompt = (i: StagePromptInput) => `${base("Stage 5A — Classroom Closure", i, "classExercise, boardSummary only")} Return exactly this JSON object: {"classExercise":["question or instruction 1","question or instruction 2"],"boardSummary":["summary point 1","summary point 2"]}. Both fields must be non-empty arrays containing only non-empty strings. Do not return strings, objects, wrappers, alternate field names, Markdown, teacherReflection, homework, comingNext, studentSummary, or any unrelated section. Keep each array concise and finish the JSON object; no placeholders.`;
export const buildStage5BPrompt = (i: StagePromptInput) => `${base("Stage 5B — Continuity & Student Work", i, "comingNext, homework, studentSummary only")} Return exactly this JSON object: {"comingNext":"complete next-step text","homework":"complete homework text","studentSummary":"complete student revision summary"}. All three fields must be non-empty strings. Do not return arrays, objects, wrappers, alternate field names, Markdown, teacherReflection, classExercise, boardSummary, or any unrelated section. Keep each value concise and finish the JSON object; no placeholders.`;
export const buildStage5Prompt = (i: StagePromptInput) => `${base("Stage 5 — Closure & Independent Work", i, "classExercise, boardSummary, comingNext, homework, studentSummary only")} Use the exact Stage 5A and Stage 5B shapes; do not return teacherReflection, reflection answers, classroom observations, student responses, or post-lesson evaluation. TeachNexis adds the uncompleted Teacher Reflection template deterministically after generation.`;
