import { getOpenRouterClient } from "@/lib/ai/providers/openrouter";
import { assembleLesson, renderLessonMarkdown } from "./v2-assembly";
import { buildStage1APrompt, buildStage1BPrompt, buildStage1CPrompt, buildStage2A1Prompt, buildTeachingContentChunkPrompt, buildStage3APrompt, buildStage3B1APrompt, buildStage3B1BPrompt, buildStage3B1CPrompt, buildStage3B2Prompt, buildStage4APrompt, buildStage4BPrompt, buildStage5APrompt, buildStage5BPrompt, type StagePromptInput } from "./v2-prompts";
import { createTeacherReflectionTemplate, type LessonMetadata, type LessonProvenance, type LessonStages, type Stage1AFoundation, type Stage1BEntryDiagnostics, type Stage1CRoadmap, type Stage2A1InstructionalContext, type Stage3AWorkedExamples, type Stage3B1AMisconceptions, type Stage3B1BActivities, type Stage3B1CDifferentiation, type Stage3B2FormativeThinking, type Stage4AApplicationsGuidance, type Stage4BExaminationItems, type Stage5AClassroomClosure, type Stage5BContinuityStudentWork, type TeachingContentChunk } from "./v2-contract";
import { assembleTeachingContentChunks, classifyStage1AShape, classifyStage1BShape, mergeStage1, mergeStage2Roadmap, mergeStage3B1Substages, mergeStage3Substages, mergeStage4Substages, mergeStage5Substages, roadmapLimitForPeriods, validateLessonContract, validateStage1A, validateStage1B, validateStage1C, validateStage2A1, validateStage3A, validateStage3B1A, validateStage3B1B, validateStage3B1C, validateStage3B2, validateStage4A, validateStage4B, validateStage5A, validateStage5B, validateStage5Generated, validateStageOutput, validateTeachingContentChunk, validateTeachingContentChunkContent } from "./v2-validation";
import { classifyJsonShape, parseStrictJsonObject, type JsonShapeDiagnostic } from "./v2-json";
import { deriveStemDeterministically } from "./v2-stem";
import { MODEL_REGISTRY } from "@/lib/ai/model-registry";

export const SHADOW_MODEL = "minimax/minimax-m3:free";
export type ShadowFailureClass = "PROVIDER_RETRYABLE" | "PROVIDER_NON_RETRYABLE" | "MODEL_CONTRACT_RETRYABLE" | "DETERMINISTIC_BLOCK";
export const SHADOW_STAGE_ENV: Record<string, string> = { "3A": "LESSON_V2_SHADOW_MODEL_3A", "3B1": "LESSON_V2_SHADOW_MODEL_3B1", "3B2": "LESSON_V2_SHADOW_MODEL_3B2", "4A": "LESSON_V2_SHADOW_MODEL_4A", "4B": "LESSON_V2_SHADOW_MODEL_4B", "5": "LESSON_V2_SHADOW_MODEL_5", "5A": "LESSON_V2_SHADOW_MODEL_5", "5B": "LESSON_V2_SHADOW_MODEL_5" };
const QUALIFICATION_MODELS = new Set(MODEL_REGISTRY.filter((entry) => entry.provider === "openrouter").map((entry) => entry.id));
export function getShadowModel(stage: ShadowStageResult["stage"]): string { const envName = SHADOW_STAGE_ENV[String(stage)]; const candidate = envName ? process.env[envName]?.trim() : undefined; return candidate && QUALIFICATION_MODELS.has(candidate) ? candidate : SHADOW_MODEL; }
export type ShadowStopReason = "PROVIDER_HTTP_FAILURE" | "STRICT_JSON_FAILURE" | "SEMANTIC_VALIDATION_FAILURE" | "LOCAL_STAGE_PROCESSING_FAILURE" | "ROADMAP_MISSING" | "STAGE_1_FAILURE" | "STAGE_2A1_FAILURE" | "ROADMAP_CHUNK_FAILURE" | "TEACHING_CONTENT_ASSEMBLY_FAILURE" | "STEM_PROCESSING_FAILURE" | "STAGE_2_MERGE_FAILURE" | "STAGE_3A_FAILURE" | "STAGE_3B1_FAILURE" | "STAGE_3B2_FAILURE" | "STAGE_4_FAILURE" | "STAGE_5_FAILURE" | "FINAL_ASSEMBLY_FAILURE" | "FINAL_VALIDATION_FAILURE";
export type ShadowStageResult = { stage: number | "1A" | "1B" | "1C" | "1-ASSEMBLY" | "2A1" | "2A_CONTENT" | "2B" | "2-ASSEMBLY" | "3A" | "3B1" | "3B1A" | "3B1B" | "3B1C" | "3B1-ASSEMBLY" | "3B2" | "4A" | "4B" | "4-ASSEMBLY" | "5A" | "5B" | "5-ASSEMBLY"; attempt?: 1 | 2; roadmapId?: string; roadmapIndex?: number; roadmapItems?: number; status: "PASS" | "BLOCKED"; httpStatus?: number; requestedModel?: string; actualModel?: string; latencyMs?: number; failureClass?: ShadowFailureClass; retryPerformed?: boolean; retryReason?: string; validationErrors: string[]; output?: unknown; shapeDiagnostic?: JsonShapeDiagnostic; stage1AShapeDiagnostic?: ReturnType<typeof classifyStage1AShape>; stage1BShapeDiagnostic?: ReturnType<typeof classifyStage1BShape> };
export type ShadowRunResult = { stages: Partial<Record<1 | 2 | 3 | 4 | 5, LessonStages[number]>>; results: ShadowStageResult[]; contract: ReturnType<typeof assembleLesson>["contract"]; assembled: boolean; finalValidation: string; wordCount: number; totalProviderCalls: number; totalRetries: number; retryStages: string[]; markdown?: string; stopReason?: ShadowStopReason; stopStage?: string; validationErrors: string[] };
export function assertShadowRunResult(value: unknown): asserts value is ShadowRunResult { if (!value || typeof value !== "object") throw new Error("Shadow orchestration returned undefined or a non-object result"); const result = value as Partial<ShadowRunResult>; if (!result.stages || !Array.isArray(result.results) || typeof result.assembled !== "boolean" || typeof result.finalValidation !== "string" || typeof result.wordCount !== "number" || typeof result.totalProviderCalls !== "number" || typeof result.totalRetries !== "number" || !Array.isArray(result.retryStages) || !Array.isArray(result.validationErrors)) throw new Error("Shadow orchestration returned an incomplete result contract"); }
export function serializeShadowStageResults(results: ShadowStageResult[]) { return results.map((result) => { const safe = { ...result }; delete safe.output; return safe; }); }
export function extractCompletionContent(completion: unknown): string | null { if (!completion || typeof completion !== "object") return null; const choices = (completion as { choices?: unknown }).choices; if (!Array.isArray(choices)) return null; const content = choices[0] && typeof choices[0] === "object" ? (choices[0] as { message?: { content?: unknown } }).message?.content : undefined; return typeof content === "string" && content.length > 0 ? content : null; }
export function extractCompletionModel(completion: unknown, fallback: string): string { return completion && typeof completion === "object" && "model" in completion && typeof (completion as { model?: unknown }).model === "string" ? (completion as { model: string }).model : fallback; }
export type ShadowTransport = (request: { stage: ShadowStageResult["stage"]; attempt: 1 | 2; model: string; prompt: string }) => Promise<unknown>;
export type ShadowRunOptions = { transport?: ShadowTransport };
export function stopReasonForStage(stage: ShadowStageResult["stage"]): ShadowStopReason { if (stage === 1 || stage === "1A" || stage === "1B" || stage === "1C") return "STAGE_1_FAILURE"; if (stage === "2A1") return "STAGE_2A1_FAILURE"; if (stage === "2A_CONTENT") return "ROADMAP_CHUNK_FAILURE"; if (stage === "2B") return "STEM_PROCESSING_FAILURE"; if (stage === "2-ASSEMBLY") return "STAGE_2_MERGE_FAILURE"; if (stage === "3A") return "STAGE_3A_FAILURE"; if (typeof stage === "string" && ["3B1", "3B1A", "3B1B", "3B1C", "3B1-ASSEMBLY"].includes(stage)) return "STAGE_3B1_FAILURE"; if (stage === "3B2") return "STAGE_3B2_FAILURE"; if (stage === 4 || stage === "4A" || stage === "4B" || stage === "4-ASSEMBLY") return "STAGE_4_FAILURE"; if (stage === 5 || stage === "5A" || stage === "5B" || stage === "5-ASSEMBLY") return "STAGE_5_FAILURE"; return "FINAL_VALIDATION_FAILURE"; }
export function classifyShadowError(stage: ShadowStageResult["stage"], message: string): ShadowStopReason { if (/is not iterable|cannot read propert|undefined|null/i.test(message)) return "LOCAL_STAGE_PROCESSING_FAILURE"; return stopReasonForStage(stage); }
export function classifyFailure(error: unknown, validation = false): ShadowFailureClass {
  if (validation) return "MODEL_CONTRACT_RETRYABLE";
  const status = typeof error === "object" && error !== null && "status" in error && typeof (error as { status?: unknown }).status === "number" ? (error as { status: number }).status : undefined;
  if (status === 401 || status === 403 || status === 429 || (status !== undefined && status >= 400 && status < 500)) return "PROVIDER_NON_RETRYABLE";
  if (status !== undefined && status >= 500) return "PROVIDER_RETRYABLE";
  const message = error instanceof Error ? error.message : typeof error === "object" && error !== null && "message" in error ? String((error as { message: unknown }).message) : String(error);
  if (/api key|credential|authentication|unauthorized|invalid model|provider configuration|configuration/i.test(message)) return "PROVIDER_NON_RETRYABLE";
  if (/raw JSON|JSON code fence|malformed JSON|JSON fence|placeholder|required field|stage shape/i.test(message)) return "MODEL_CONTRACT_RETRYABLE";
  if (/timeout|timed out|network|fetch failed|connection|socket|empty model response/i.test(message)) return "PROVIDER_RETRYABLE";
  if (/roadmap|source evidence|provenance|deterministic|identity|order/i.test(message)) return "DETERMINISTIC_BLOCK";
  return "PROVIDER_RETRYABLE";
}
const makeProvenance = (metadata: LessonMetadata): LessonProvenance => ({ origin: "AI_GENERATED", sourceLocations: [], extracted: false, generated: true, aiTransformedSource: false, teacherEditState: "NOT_REVIEWED", provider: "openrouter", requestedModel: SHADOW_MODEL, actualModel: null, generatedAt: new Date().toISOString(), templateVersion: "TEACHNEXIS_LESSON_V2", curriculumContextUsed: metadata.curriculumLabels.length > 0, textbookContextUsed: false, stages: {} });
type Validation = { status: string; errors: { message: string; code?: string }[] };
export function classifyValidationFailure(errors: Validation["errors"]): ShadowFailureClass { const deterministicCodes = new Set(["SOURCE_EVIDENCE_REQUIRED", "GENERATED_SOURCE_EVIDENCE", "INVALID_SOURCE_STATUS", "CHUNK_ORDER", "CHUNK_ROADMAP_MISMATCH", "CHUNK_DUPLICATE", "CHUNK_MISSING"]); return errors.some((error) => error.code && deterministicCodes.has(error.code)) ? "DETERMINISTIC_BLOCK" : "MODEL_CONTRACT_RETRYABLE"; }

export async function runLessonV2Shadow(input: StagePromptInput, options: ShadowRunOptions = {}): Promise<ShadowRunResult> {
  const results: ShadowStageResult[] = []; const stages: Partial<Record<1 | 2 | 3 | 4 | 5, LessonStages[number]>> = {}; const p = makeProvenance(input.metadata);
  const call = async (stage: ShadowStageResult["stage"], prompt: string, validate: (value: unknown) => Validation, diagnostic?: (value: unknown) => unknown) => {
    const requestedModel = getShadowModel(stage);
    for (const attempt of [1, 2] as const) {
      const started = Date.now(); let raw: string | null = null;
      try {
        const completion = options.transport ? await options.transport({ stage, attempt, model: requestedModel, prompt }) : await getOpenRouterClient(requestedModel).chat.completions.create({ model: requestedModel, messages: [{ role: "user", content: prompt }], max_tokens: 1800, temperature: 0.2, response_format: { type: "json_object" } }, { signal: AbortSignal.timeout(90000) });
        const actualModel = extractCompletionModel(completion, requestedModel);
        raw = extractCompletionContent(completion); if (!raw) throw new Error("Empty model response");
        const payload = parseStrictJsonObject(raw); const enrichedPayload = { ...payload, metadata: input.metadata, provenance: p }; const check = validate(enrichedPayload);
        if (check.status === "BLOCKED") {
          const failureClass = classifyValidationFailure(check.errors); const retry = attempt === 1 && failureClass === "MODEL_CONTRACT_RETRYABLE";
          const validationResult: ShadowStageResult = { stage, attempt, status: "BLOCKED", httpStatus: 200, requestedModel, actualModel, latencyMs: Date.now() - started, failureClass, retryPerformed: retry, retryReason: retry ? "Model contract validation failure" : undefined, validationErrors: check.errors.map((x) => x.message) }; if (diagnostic) { if (stage === "1B") validationResult.stage1BShapeDiagnostic = diagnostic(payload) as ReturnType<typeof classifyStage1BShape>; else if (stage === "1A") validationResult.stage1AShapeDiagnostic = diagnostic(payload) as ReturnType<typeof classifyStage1AShape>; } results.push(validationResult);
          if (!retry || failureClass !== "MODEL_CONTRACT_RETRYABLE") return null;
          continue;
        }
        results.push({ stage, attempt, status: "PASS", httpStatus: 200, requestedModel, actualModel, latencyMs: Date.now() - started, validationErrors: [] }); return { payload: enrichedPayload, completionModel: actualModel };
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error); const failureClass = classifyFailure(error); const retry = attempt === 1 && failureClass === "PROVIDER_RETRYABLE"; const parseFailure = /raw JSON|JSON code fence|malformed JSON|JSON fence|Empty model response/i.test(message);
        results.push({ stage, attempt, status: "BLOCKED", requestedModel, latencyMs: Date.now() - started, failureClass: parseFailure ? "MODEL_CONTRACT_RETRYABLE" : failureClass, retryPerformed: retry || (attempt === 1 && parseFailure), retryReason: (retry || parseFailure) ? "Retryable provider/structured-output failure" : undefined, validationErrors: [message], ...(parseFailure && raw ? { shapeDiagnostic: classifyJsonShape(raw) } : {}) });
        if (attempt === 1 && (retry || parseFailure)) continue;
        return null;
      }
    }
    return null;
  };
  const summary = () => ({ totalProviderCalls: results.filter((x) => x.httpStatus !== undefined).length, totalRetries: results.filter((x) => x.attempt === 2).length, retryStages: [...new Set(results.filter((x) => x.attempt === 2).map((x) => String(x.stage)))] });
  const fail = (stage: ShadowStageResult["stage"], reason: ShadowStopReason, errors?: string[]): ShadowRunResult => ({ stages, results, contract: null, assembled: false, finalValidation: "BLOCKED", wordCount: 0, stopReason: reason, stopStage: String(stage), validationErrors: errors ?? results.at(-1)?.validationErrors ?? [`${String(stage)} failed`], ...summary() });
  const a = await call("1A", buildStage1APrompt(input), (v) => validateStage1A({ ...(v as object), stage: "1A", metadata: input.metadata, provenance: p }), classifyStage1AShape); if (!a) return fail("1A", classifyShadowError("1A", results.at(-1)?.validationErrors[0] ?? ""));
  const b = await call("1B", buildStage1BPrompt(input), (v) => validateStage1B({ ...(v as object), stage: "1B", metadata: input.metadata, provenance: p }), classifyStage1BShape); if (!b) return fail("1B", "STAGE_1_FAILURE");
  const maxRoadmap = roadmapLimitForPeriods(input.metadata.periods); const c = await call("1C", buildStage1CPrompt(input), (v) => validateStage1C({ ...(v as object), stage: "1C", metadata: input.metadata, provenance: p } as unknown as Stage1CRoadmap, maxRoadmap)); if (!c) return fail("1C", "STAGE_1_FAILURE");
  const merged1 = mergeStage1(a.payload as unknown as Stage1AFoundation, b.payload as unknown as Stage1BEntryDiagnostics, c.payload as unknown as Stage1CRoadmap); const merged1Check = validateStageOutput(1, { ...merged1, metadata: input.metadata, provenance: p }); results.push({ stage: "1-ASSEMBLY", status: merged1Check.status === "BLOCKED" ? "BLOCKED" : "PASS", latencyMs: 0, roadmapItems: merged1.curriculum.roadmap.length, validationErrors: merged1Check.errors.map((x) => x.message) }); if (merged1Check.status === "BLOCKED") return fail("1-ASSEMBLY", "STAGE_1_FAILURE", merged1Check.errors.map((x) => x.message)); stages[1] = merged1;
  const roadmap = merged1.curriculum.roadmap.map((item, index) => ({ ...item, id: `roadmap-${index + 1}` })); if (!roadmap.length) return fail("1-ASSEMBLY", "ROADMAP_MISSING", ["Stage 1 returned no roadmap items"]);
  const a1 = await call("2A1", buildStage2A1Prompt(input), (v) => validateStage2A1({ ...(v as object), stage: "2A1", metadata: input.metadata, provenance: p } as unknown as Stage2A1InstructionalContext)); if (!a1) return fail("2A1", "STAGE_2A1_FAILURE"); const stage2a1 = { ...(a1.payload as object), stage: "2A1" as const, metadata: input.metadata, provenance: p } as Stage2A1InstructionalContext; const chunks: TeachingContentChunk[] = [];
  for (const [index, item] of roadmap.entries()) { const chunk = await call("2A_CONTENT", buildTeachingContentChunkPrompt(input, item.id, index, item.title), (v) => validateTeachingContentChunkContent(v)); const latest = results.at(-1); if (latest) { latest.roadmapId = item.id; latest.roadmapIndex = index; } if (!chunk) return fail("2A_CONTENT", "ROADMAP_CHUNK_FAILURE", latest?.validationErrors); const content = (chunk.payload as { content?: unknown }).content; const authoritativeChunk = { stage: "2A_CONTENT" as const, metadata: input.metadata, provenance: p, roadmapId: item.id, roadmapIndex: index, title: item.title, content: content as string }; const identityCheck = validateTeachingContentChunk(authoritativeChunk, roadmap, index); if (identityCheck.status === "BLOCKED") return fail("2A_CONTENT", "ROADMAP_CHUNK_FAILURE", identityCheck.errors.map((x) => x.message)); chunks.push(authoritativeChunk); }
  const contentCheck = assembleTeachingContentChunks(chunks, roadmap); results.push({ stage: "2-ASSEMBLY", status: contentCheck.status === "BLOCKED" ? "BLOCKED" : "PASS", latencyMs: 0, roadmapItems: roadmap.length, validationErrors: contentCheck.errors.map((x) => x.message) }); if (contentCheck.status === "BLOCKED") return fail("2-ASSEMBLY", "TEACHING_CONTENT_ASSEMBLY_FAILURE", contentCheck.errors.map((x) => x.message));
  const stage2b = { stage: "2B" as const, metadata: input.metadata, provenance: p, stem: deriveStemDeterministically({ origin: input.contentOrigin ?? "AI_GENERATED", sourceRepresentation: input.stemSource, warnings: input.stemWarnings }, contentCheck.teachingContent) }; results.push({ stage: "2B", status: "PASS", latencyMs: 0, validationErrors: [] }); const merged2 = mergeStage2Roadmap(stage2a1, chunks, stage2b, roadmap); if (!merged2) return fail("2-ASSEMBLY", "STAGE_2_MERGE_FAILURE"); stages[2] = merged2;
  const s3a = await call("3A", buildStage3APrompt(input), (v) => validateStage3A({ ...(v as object), stage: "3A", metadata: input.metadata, provenance: p } as Stage3AWorkedExamples)); if (!s3a) return fail("3A", "STAGE_3A_FAILURE");
  const s3b1a = await call("3B1A", buildStage3B1APrompt(input), (v) => validateStage3B1A(v)); if (!s3b1a) return fail("3B1A", "STAGE_3B1_FAILURE");
  const s3b1b = await call("3B1B", buildStage3B1BPrompt(input), (v) => validateStage3B1B(v)); if (!s3b1b) return fail("3B1B", "STAGE_3B1_FAILURE");
  const s3b1c = await call("3B1C", buildStage3B1CPrompt(input), (v) => validateStage3B1C(v)); if (!s3b1c) return fail("3B1C", "STAGE_3B1_FAILURE");
  const mergedB1 = mergeStage3B1Substages({ ...(s3b1a.payload as object), stage: "3B1A", metadata: input.metadata, provenance: p } as Stage3B1AMisconceptions, { ...(s3b1b.payload as object), stage: "3B1B", metadata: input.metadata, provenance: p } as Stage3B1BActivities, { ...(s3b1c.payload as object), stage: "3B1C", metadata: input.metadata, provenance: p } as Stage3B1CDifferentiation); results.push({ stage: "3B1-ASSEMBLY", status: "PASS", latencyMs: 0, validationErrors: [] });
  const s3b2 = await call("3B2", buildStage3B2Prompt(input), (v) => validateStage3B2({ ...(v as object), stage: "3B2", metadata: input.metadata, provenance: p } as Stage3B2FormativeThinking)); if (!s3b2) return fail("3B2", "STAGE_3B2_FAILURE"); stages[3] = mergeStage3Substages({ ...(s3a.payload as object), stage: "3A", metadata: input.metadata, provenance: p } as Stage3AWorkedExamples, mergedB1, { ...(s3b2.payload as object), stage: "3B2", metadata: input.metadata, provenance: p } as Stage3B2FormativeThinking);
  const s4a = await call("4A", buildStage4APrompt(input), (v) => validateStage4A(v)); if (!s4a) return fail("4A", "STAGE_4_FAILURE");
  const s4b = await call("4B", buildStage4BPrompt(input), (v) => validateStage4B(v)); if (!s4b) return fail("4B", "STAGE_4_FAILURE");
  const stage4 = mergeStage4Substages({ ...(s4a.payload as object), stage: "4A", metadata: input.metadata, provenance: p } as Stage4AApplicationsGuidance, { ...(s4b.payload as object), stage: "4B", metadata: input.metadata, provenance: p } as Stage4BExaminationItems);
  const stage4Check = validateStageOutput(4, { ...stage4, metadata: input.metadata, provenance: p }); results.push({ stage: "4-ASSEMBLY", status: stage4Check.status === "BLOCKED" ? "BLOCKED" : "PASS", latencyMs: 0, validationErrors: stage4Check.errors.map((x) => x.message) }); if (stage4Check.status === "BLOCKED") return fail("4-ASSEMBLY", "STAGE_4_FAILURE", stage4Check.errors.map((x) => x.message)); stages[4] = stage4;
  const result5a = await call("5A", buildStage5APrompt(input), (v) => validateStage5A(v)); if (!result5a) return fail("5A", "STAGE_5_FAILURE"); const result5b = await call("5B", buildStage5BPrompt(input), (v) => validateStage5B(v)); if (!result5b) return fail("5B", "STAGE_5_FAILURE"); const stage5 = mergeStage5Substages({ ...(result5a.payload as object), stage: "5A", metadata: input.metadata, provenance: p } as Stage5AClassroomClosure, { ...(result5b.payload as object), stage: "5B", metadata: input.metadata, provenance: p } as Stage5BContinuityStudentWork); const stage5Check = validateStage5Generated(stage5); results.push({ stage: "5-ASSEMBLY", status: stage5Check.status === "BLOCKED" ? "BLOCKED" : "PASS", latencyMs: 0, validationErrors: stage5Check.errors.map((x) => x.message) }); if (stage5Check.status === "BLOCKED") return fail("5-ASSEMBLY", "STAGE_5_FAILURE", stage5Check.errors.map((x) => x.message)); stages[5] = { ...stage5, teacherReflection: createTeacherReflectionTemplate() } as LessonStages[number];
  const assembled = assembleLesson(stages); if (!assembled.contract) return fail(6, "FINAL_ASSEMBLY_FAILURE"); const final = validateLessonContract(assembled.contract, input.metadata); results.push({ stage: 6, status: final.status === "BLOCKED" ? "BLOCKED" : "PASS", validationErrors: final.errors.map((x) => x.message), output: final }); if (final.status === "BLOCKED") return fail(6, "FINAL_VALIDATION_FAILURE", final.errors.map((x) => x.message)); const markdown = renderLessonMarkdown(assembled.contract); return { stages, results, contract: assembled.contract, assembled: true, finalValidation: final.status, wordCount: markdown.trim().split(/\s+/).filter(Boolean).length, markdown, validationErrors: [], ...summary() };
}
