import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "TeachFlow OS terms of service for Nigerian schools and educators.",
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-20">
      <Link href="/" className="text-sm text-primary mb-8 inline-block hover:underline">
        &larr; Back to TeachFlow OS
      </Link>
      <h1 className="text-3xl font-bold text-text mb-6">Terms of Service</h1>
      <div className="prose prose-slate max-w-none text-text-2 space-y-4 text-sm leading-relaxed">
        <p>Last updated: June 2026</p>
        <h2 className="text-lg font-semibold text-text mt-8">1. Acceptance</h2>
        <p>By accessing TeachFlow OS you agree to these terms. TeachFlow OS is an AI-powered education platform for Nigerian secondary schools (JSS1-SS3).</p>
        <h2 className="text-lg font-semibold text-text mt-8">2. Use of Service</h2>
        <p>TeachFlow OS is provided free of charge for educational use. You may not use the platform for any unlawful purpose or to harm other users.</p>
        <h2 className="text-lg font-semibold text-text mt-8">3. AI-Generated Content</h2>
        <p>Lesson plans, exam questions, and study materials are generated by AI models. While aligned with WAEC, JAMB, and JUPEB curricula, teachers should review all generated content before classroom use.</p>
        <h2 className="text-lg font-semibold text-text mt-8">4. Data</h2>
        <p>Student and school data is stored securely and used only to provide the service. We do not sell user data to third parties.</p>
        <h2 className="text-lg font-semibold text-text mt-8">5. Contact</h2>
        <p>For questions about these terms, contact us at judithluchi@gmail.com.</p>
      </div>
    </main>
  );
}
